### ISSUE TITLE
broker's exceptions are thrown when any other mqtt-client publish data

### ISSUE THREAD

**Issue by yutouhewo** [eclipse/kapua#1112]
hi all, i will get these exception below when i start the 'kura-simulator'  like
"java -jar kapua-simulator-kura-0.3.0-SNAPSHOT-app.jar -f ../src/test/resources/example1.json "

why ?
thanks

``` 
CamelJmsDeliveryMode=1, ActiveMQ_DOT_MQTT_DOT_QoS=0, originalTopic=kapua-sys.sim-1.example1.t1.data}, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false}	at org.apache.camel.component.jms.JmsBinding.extractBodyFromJms(JmsBinding.java:160)
	at org.apache.camel.component.jms.JmsMessage.createBody(JmsMessage.java:236)
	at org.apache.camel.impl.MessageSupport.getBody(MessageSupport.java:41)
	at org.apache.camel.impl.DefaultUnitOfWork.<init>(DefaultUnitOfWork.java:90)
	at org.apache.camel.impl.DefaultUnitOfWork.<init>(DefaultUnitOfWork.java:72)
	at org.apache.camel.impl.DefaultUnitOfWorkFactory.createUnitOfWork(DefaultUnitOfWorkFactory.java:34)
	at org.apache.camel.processor.CamelInternalProcessor$UnitOfWorkProcessorAdvice.createUnitOfWork(CamelInternalProcessor.java:663)
	at org.apache.camel.processor.CamelInternalProcessor$UnitOfWorkProcessorAdvice.before(CamelInternalProcessor.java:631)
	at org.apache.camel.processor.CamelInternalProcessor$UnitOfWorkProcessorAdvice.before(CamelInternalProcessor.java:608)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:138)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:689)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:649)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:619)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:307)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:245)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1144)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1136)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1033)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.jms.JMSException: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: Forbidden c
lass org.eclipse.kapua.broker.core.message.CamelKapuaMessage! This class is not trusted to be serialized as ObjectMessage payload. Please take a look at http://activemq.apache.org/objectmessage.html for more information on how to configure trusted classes.	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:208)
	at org.apache.camel.component.jms.JmsBinding.extractBodyFromJms(JmsBinding.java:135)
	... 23 common frames omitted
Caused by: java.lang.ClassNotFoundException: Forbidden class org.eclipse.kapua.broker.core.message.CamelKapuaMessage! This class is not trusted to be serialized as Obj
ectMessage payload. Please take a look at http://activemq.apache.org/objectmessage.html for more information on how to configure trusted classes.	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.checkSecurity(ClassLoadingAwareObjectInputStream.java:112)
	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.resolveClass(ClassLoadingAwareObjectInputStream.java:57)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:206)
	... 24 common frames omitted
```

**Comment by ctron** [comment]
Hi @yutouhewo 

I am little bit confused how that could be. Since the simulator uses neither Camel nor spring.

Maybe you could explain what your actual system setup is, from which process the log output is, …

Otherwise it will be hard to help you.

**Comment by yutouhewo** [comment]
@ctron , thanks for your suggestion, I was running the broker with "./activemq console"  and listenning the client's connections, the exception's logs above was copied by the process of activemq (console's print).

My purpose is extracting the services like h2, broker, console .etc from the docker's images and running them alone. By the way, by running all docker's containers is ok when I test the 'kura-simulator'. 

I also have got the exception logs like below, When any other mqtt's client trying to publish datas
... ...
java.lang.SecurityException: User 1:kapua-broker (test - tcp://172.10.1.250:43044 - conn id 8311751204660430619) is not authorized to read from: topic://VirtualTopic.k
ura.test.myapp.xmltopic	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.internalAddConsumer(KapuaSecurityBrokerFilter.java:793)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConsumer(KapuaSecurityBrokerFilter.java:748)
	at org.apache.activemq.broker.BrokerFilter.addConsumer(BrokerFilter.java:103)
	at org.apache.activemq.broker.MutableBrokerFilter.addConsumer(MutableBrokerFilter.java:108)
	at org.apache.activemq.broker.TransportConnection.processAddConsumer(TransportConnection.java:706)
	at org.apache.activemq.command.ConsumerInfo.visit(ConsumerInfo.java:351)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)
	at org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)
	at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.doSubscribe(AbstractMQTTSubscriptionStrategy.java:210)
	at org.apache.activemq.transport.mqtt.strategy.MQTTVirtualTopicSubscriptionStrategy.onSubscribe(MQTTVirtualTopicSubscriptionStrategy.java:118)
	at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.onSubscribe(AbstractMQTTSubscriptionStrategy.java:118)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onSubscribe(MQTTProtocolConverter.java:387)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:213)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)
	at org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)
	at org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.processBuffer(MQTTNIOTransport.java:132)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.serviceRead(MQTTNIOTransport.java:120)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.access$000(MQTTNIOTransport.java:43)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)
	at org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)
	at org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:16:05.580 [ActiveMQ NIO Worker 4] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User 1:kapua-broker (test - tcp://172.10.1.250:43044 - conn id 8311751204660430619) 
is not authorized to write to: topic://VirtualTopic.kura.test.heater.data

**Comment by ctron** [comment]
Thanks for adding some context.

So to me this has nothing to do with the simulator, but with modifications you made to the broker/system.

**Comment by yutouhewo** [comment]
@ctron  , yep, simulator is ok, but I'm just confused with the errors by "...is not authorized..." thrown by broker actually. Is that mean "kapua-broker" roles is forbidden or the mqtt-client's data is invalid?

**Comment by ctron** [comment]
So I would suggest to re-phrase the subject of this issue so that people know what this is about.

**Comment by riccardomodanese** [comment]
About https://github.com/eclipse/kapua/issues/1112#issue-278688108 if I understood correctly you extracted the broker form the docker image right?
From the log the issue is located in the ActiveMQ configuration.
It's not clear to me why the right parameter setting is missing (can you provide more information about how you are extracting the broker from the docker image?)
In any case by overriding manually the ActiveMQ serializable packages should solve the issue (this setting is for debug purpose, please restrict the packages in a production like environment)

```
export ACTIVEMQ_OPTS="${ACTIVEMQ_OPTS} -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"
```

About https://github.com/eclipse/kapua/issues/1112#issuecomment-349163353 can you provide more information about the users used to connect to the broker, the clients id you used and in which topics each client is publishing/subscribing?

**Comment by yutouhewo** [comment]
@riccardomodanese 
First of all, thanks very much!  :）
1. About the broker's extracting by using the CMD like:  
` sudo docker cp 54bddb818b04:/maven /home/kapua/activemq`
   and I didn't change anything of the configurations within the directory of 'XXX/conf'

2. About the mqtt-cilent, I ran the demo based on the library of paho. The main source like below:
`import java.io.UnsupportedEncodingException;

import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

public class MqttPublishSample {
	public static void main(String[] args) throws InterruptedException, UnsupportedEncodingException {

		// {account-name}/{connectionClientId}/{semanticTopic}
		String topic = "kapua-broker/sim-2/test";
		String content = "Message from MqttPublishSample";
		int qos = 2;
		String broker = "tcp://172.10.1.103:1884";
		String clientId = "sim-2";
		MemoryPersistence persistence = new MemoryPersistence();

		try {
			MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
			MqttConnectOptions connOpts = new MqttConnectOptions();
			connOpts.setCleanSession(true);
			connOpts.setUserName("kapua-broker");
			connOpts.setPassword("kapua-password".toCharArray());
			
			System.out.println("Connecting to broker: " + broker);
			
			
			sampleClient.connect(connOpts);
			System.out.println("Connected");
			
			for (int i = 0; i < 99999; i++) {
				//String msg = "" + i;
				MqttMessage message = new MqttMessage(content.getBytes("UTF-8"));

				message.setQos(qos);
				sampleClient.publish(topic, message);
				
				System.out.println("Publishing message: " + message);
				
				//System.out.println("Message published");	
				
				Thread.sleep(1000);
			}

			sampleClient.disconnect();
			System.out.println("Disconnected");
			System.exit(0);
		} catch (MqttException me) {
			System.out.println("reason " + me.getReasonCode());
			System.out.println("msg " + me.getMessage());
			System.out.println("loc " + me.getLocalizedMessage());
			System.out.println("cause " + me.getCause());
			System.out.println("excep " + me);
			me.printStackTrace();
		}
	}
}
`
**But right now, I got the new exception like this, if I did some basic mistake?! Confuse me now...**
17:45:49.776 [ActiveMQ NIO Worker 2] INFO  o.e.k.b.c.p.KapuaSecurityBrokerFilter - @@ error
java.lang.SecurityException: User not authorized!
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.checkConnectionCountByReservedUserId(KapuaSecurityBrokerFilter.java:557)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.enforceDeviceUserBound(KapuaSecurityBrokerFilter.java:541)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.enforceDeviceConnectionUserBound(KapuaSecurityBrokerFilter.java:511)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addExternalConnection(KapuaSecurityBrokerFilter.java:395)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConnection(KapuaSecurityBrokerFilter.java:288)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:98)
	at org.apache.activemq.broker.MutableBrokerFilter.addConnection(MutableBrokerFilter.java:103)
	at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:852)
	at org.apache.activemq.broker.jmx.ManagedTransportConnection.processAddConnection(ManagedTransportConnection.java:77)
	at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)
	at org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTConnect(MQTTProtocolConverter.java:310)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:205)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)
	at org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)
	at org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.processBuffer(MQTTNIOTransport.java:132)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.serviceRead(MQTTNIOTransport.java:120)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.access$000(MQTTNIOTransport.java:43)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)
	at org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)
	at org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:45:49.778 [ActiveMQ NIO Worker 2] WARN  o.a.a.broker.TransportConnection - Failed to add Connection id=ID:adsl-172-10-1-103.dsl.sndg02.sbcglobal.net-41658-151255326
7656-3:5, clientId=sim-2 due to {}

**Comment by riccardomodanese** [comment]
From the log it seem you enabled the connection-user coupling feature. So your device is set to use a user name in exclusively way (so the user cannot be used by any other device) and you are trying to connect a different device using that user.
Can you check the connection settings through the console connection view?

P.S. Which Kapua version are you using (0.3.0?)

**Comment by yutouhewo** [comment]
@riccardomodanese 
Hi, the connection is successful through the console's view, and the Kapua version is 0.3.0
![image](https://user-images.githubusercontent.com/1351235/33662192-e73df02e-dac5-11e7-8621-0fd7523f95a7.png)

And the errors are always like that:
`20:43:36.712 [ActiveMQ NIO Worker 1] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://172.10.1.119:49912, User 1:kapua-broke
r (sim-2 - tcp://172.10.1.119:49912 - conn id 5001794574555475621) is not authorized to write to: topic://VirtualTopic.kapua-broker.sim-2.test20:43:36.712 [ActiveMQ NIO Worker 1] WARN  o.a.a.t.mqtt.MQTTProtocolConverter - Failed to send MQTT Publish:`

**Comment by riccardomodanese** [comment]
I'm investigating about the error you reported.

In the meanwhile, about your P.S.:
for the Kapua platform the physical network connection is separeted from the device.
So a connected "entity" to become a device needs to send a "presentation" message (the BIRTH message).
For that reason, until you don't send a birth message, you cannot see your device in the device view (but you can see the connection your device is using in the connection view).

To emulate the BIRTH message from your own client code you can take a look to these 2 links (the BIRTH message is just an MQTT message, with several prefixed metrics names, sent to a specific topic).

https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/message/KuraBirthPayload.java

https://github.com/eurotech/edc-examples/tree/master/edc-java-client

**Comment by riccardomodanese** [comment]
I tested the broker and it works fine. So looking back to your log I'm thinking you are using the wrong account name when building the publish/subscribe topics.
According to the default user seeding, if you are using kapua-broker as user, the account name is kapua-sys.
If you change the topic from:
```
kapua-broker/sim-2/test20:43:36.712
```
to
```
kapua-sys/sim-2/test20:43:36.712
```
it should work.

**Comment by yutouhewo** [comment]
@riccardomodanese 
Sorry to bother you again :)
Now, I suppose not foucs on sending a "presentation" message (the BIRTH message) .I'm just using simulator-kura to publish like:
`java -jar kapua-simulator-kura-0.3.0-SNAPSHOT-app.jar -a kapua-sys -b tcp://kapua-broker:kapua-password@localhost:1884 -f ../src/test/resources/example1.json`

after that, the status of my broker's connection-view and device-view all are green(Green is ok, right?), but I cannot see the data when I choose the Data-Button, and the exceptions are below:

Copied from kapua-broker:
```
09:08:30.648 [Camel (camelContext) thread #19 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  org.eclipse.kapua.KapuaException
 - Could not load Exception Messages Bundle for Locale en_US09:08:30.649 [Camel (camelContext) thread #19 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  o.a.c.processor.DeadLetterChanne
l - Failed delivery for (MessageId: ID:adsl-172-10-1-103.dsl.sndg02.sbcglobal.net-35592-1512608888890-3:1:-1:1:2 on ExchangeId: ID-adsl-172-10-1-103-dsl-sndg02-sbcglobal-net-41374-1512608892317-0-2). On delivery attempt: 0 caught: org.eclipse.kapua.service.datastore.internal.mediator.DatastoreException: An internal error occurred: {0}.09:08:31.649 [Camel (camelContext) thread #14 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  org.eclipse.kapua.KapuaException
 - Could not load Exception Messages Bundle for Locale en_US09:08:31.651 [Camel (camelContext) thread #14 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  o.a.c.processor.DeadLetterChanne
l - Failed delivery for (MessageId: ID:adsl-172-10-1-103.dsl.sndg02.sbcglobal.net-35592-1512608888890-3:1:-1:1:4 on ExchangeId: ID-adsl-172-10-1-103-dsl-sndg02-sbcglobal-net-41374-1512608892317-0-4). On delivery attempt: 0 caught: org.eclipse.kapua.service.datastore.internal.mediator.DatastoreException: An internal error occurred: {0}.09:08:31.671 [Camel (camelContext) thread #24 - JmsConsumer[storeGenericException]] INFO  o.e.k.b.c.l.DataStorageMessageProcessor - Message datastoreId: 'b970dc4b-e18d
-4f1b-a133-5d7e0f3f0627' - Message Id 'null'09:08:32.653 [Camel (camelContext) thread #8 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  org.eclipse.kapua.KapuaException 
- Could not load Exception Messages Bundle for Locale en_US09:08:32.654 [Camel (camelContext) thread #8 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  o.a.c.processor.DeadLetterChannel
 - Failed delivery for (MessageId: ID:adsl-172-10-1-103.dsl.sndg02.sbcglobal.net-35592-1512608888890-3:1:-1:1:5 on ExchangeId: ID-adsl-172-10-1-103-dsl-sndg02-sbcglobal-net-41374-1512608892317-0-5). On delivery attempt: 0 caught: org.eclipse.kapua.service.datastore.internal.mediator.DatastoreException: An internal error occurred: {0}.
```

Copied from kapua-console:
```
352343 [qtp391447681-12] ERROR o.e.k.a.c.m.a.s.u.KapuaExceptionHandler - internal service error 
org.eclipse.kapua.KapuaException: An internal error occurred: Error: .
	at org.eclipse.kapua.KapuaException.internalError(KapuaException.java:143)
	at org.eclipse.kapua.service.datastore.internal.ChannelInfoRegistryServiceImpl.query(ChannelInfoRegistryServiceImpl.java:136)
	at org.eclipse.kapua.app.console.module.data.server.GwtDataServiceImpl.findTopicsTree(GwtDataServiceImpl.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.eclipse.kapua.app.console.core.filter.KapuaWebFilter.executeChain(KapuaWebFilter.java:43)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.kapua.service.datastore.client.ClientException: Error: 
	at org.eclipse.kapua.service.datastore.client.rest.RestDatastoreClient.restCallTimeoutHandler(RestDatastoreClient.java:701)
	at org.eclipse.kapua.service.datastore.client.rest.RestDatastoreClient.query(RestDatastoreClient.java:391)
	at org.eclipse.kapua.service.datastore.internal.ChannelInfoRegistryFacade.query(ChannelInfoRegistryFacade.java:223)
	at org.eclipse.kapua.service.datastore.internal.ChannelInfoRegistryServiceImpl.query(ChannelInfoRegistryServiceImpl.java:127)
	... 51 common frames omitted
Caused by: java.net.ConnectException: null
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	... 1 common frames omitted

```

P.S. Refer to you suggestion, I figure out the question of "Caused by: java.lang.ClassNotFoundException: Forbidden class org.eclipse.kapua.broker.core.message.CamelKapuaMessage"  temprorary!  THKs  :)
`export ACTIVEMQ_OPTS="${ACTIVEMQ_OPTS} -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"`

**Comment by yutouhewo** [comment]
@riccardomodanese 
Hallelu Yah  :)  haha
Thanks very very...much, everythings work perfectly now!
The next step, I will try to send the "presentation" message (the BIRTH message).

P.S. About the env-variables like:
`export ACTIVEMQ_OPTS="${ACTIVEMQ_OPTS} -Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*"`
Is there any conf's file in project which I could modify or not?

**Comment by riccardomodanese** [comment]
You are welcome!

I'm inspecting the docker image since apparently the serializable packages are not overwritten by a customized configuration.
In any case, to solve your issue, you can add the 

```
-Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*
```
by seeding the bin/env file inside the broker docker image at build time or replacing it with a customized version.
It should work.
