### ISSUE TITLE
Kapua-broker throws exceptios like "...is  not authorized to read from: topic..."

### ISSUE THREAD

**Issue by yutouhewo** [eclipse/kapua#1130]
Hi all, The context:
1. I run the broker alone with "./activemq console" and listenning the port ":1884";
2. run the simualtor testing with "java -jar kapua-simulator-kura-0.3.0-SNAPSHOT-app.jar -a kapua-broker -b tcp://kapua-broker:kapua-password@localhost:1884 -f ../src/test/resources/example1.json";

the cosole's print exceptions below like:

```
14:51:10.087 [ActiveMQ NIO Worker 2] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User 1:kapua-broker (sim-1 - tcp://127.0.0.1:45476 - conn id 4858748371498281608) is
 not authorized to read from: topic://VirtualTopic.$EDC.kapua-broker.sim-1.DEPLOY-V2.>14:51:10.088 [ActiveMQ NIO Worker 2] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://127.0.0.1:45476, User 1:kapua-broker (
sim-1 - tcp://127.0.0.1:45476 - conn id 4858748371498281608) is not authorized to read from: topic://VirtualTopic.$EDC.kapua-broker.sim-1.DEPLOY-V2.>14:51:10.089 [ActiveMQ NIO Worker 2] WARN  o.a.a.t.m.s.AbstractMQTTSubscriptionStrategy - Error subscribing to $EDC/kapua-broker/sim-1/DEPLOY-V2/#
java.lang.SecurityException: User 1:kapua-broker (sim-1 - tcp://127.0.0.1:45476 - conn id 4858748371498281608) is not authorized to read from: topic://VirtualTopic.$ED
C.kapua-broker.sim-1.DEPLOY-V2.>	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.internalAddConsumer(KapuaSecurityBrokerFilter.java:793)
	at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.addConsumer(KapuaSecurityBrokerFilter.java:748)
	at org.apache.activemq.broker.BrokerFilter.addConsumer(BrokerFilter.java:103)
	at org.apache.activemq.broker.MutableBrokerFilter.addConsumer(MutableBrokerFilter.java:108)
	at org.apache.activemq.broker.TransportConnection.processAddConsumer(TransportConnection.java:706)
	at org.apache.activemq.command.ConsumerInfo.visit(ConsumerInfo.java:351)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)
	at org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)
	at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.doSubscribe(AbstractMQTTSubscriptionStrategy.java:210)
	at org.apache.activemq.transport.mqtt.strategy.MQTTVirtualTopicSubscriptionStrategy.onSubscribe(MQTTVirtualTopicSubscriptionStrategy.java:118)
	at org.apache.activemq.transport.mqtt.strategy.AbstractMQTTSubscriptionStrategy.onSubscribe(AbstractMQTTSubscriptionStrategy.java:118)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onSubscribe(MQTTProtocolConverter.java:387)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:213)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)
	at org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)
	at org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.processBuffer(MQTTNIOTransport.java:132)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.serviceRead(MQTTNIOTransport.java:120)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.access$000(MQTTNIOTransport.java:43)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)
	at org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)
	at org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by riccardomodanese** [comment]
As for the https://github.com/eclipse/kapua/issues/1112#issuecomment-349583578 can you provide information about the client id/user/topics?
