### ISSUE TITLE
Error And Freeze When Starting Or Stopping Bundle On Live Device

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1313]
When a live device is connected to Kapua, a error pops-up when a bundle is started/stopped (Example Publisher in this case) several times and also the Bundle window freezes 

Testflow: 
1. Login as kapua-sys
2. Connect live devcise to Kapua (e.g. device1) with installed Example Publisher, Heater or any other sample package
3. Go to Devices, select the live device1
4. Go to Bundles and try to start/stop one of the bundles (Example Publisher in this case)

Screenshot No. 1 (Error when bundle is started/stopped several times): 
![bundle-start-stop](https://user-images.githubusercontent.com/15121999/35100870-a9e2c09c-fc5d-11e7-80bd-444c8ccf73ab.png)

Screenshot No. 2 (Bundle window freezing when bundle is started/stopped several times): 
<img width="1371" alt="screen shot 2018-01-19 at 10 13 16" src="https://user-images.githubusercontent.com/15121999/35143228-3e3a6fc6-fd01-11e7-886f-afacabaefdd7.png">

Browsers used:
- Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)))
- Safari (Version 11.0.2 (13604.3.5))
- Mozilla Firefox (57.0.4 (64-bit))
- Opera (Version 50.0.2762.45)

**Comment by lorthirk** [comment]
After some starting and stopping, this is the error stack trace. The error seems to be somewhat random anyway, since it only appears sometimes.

```
89315844 [qtp940060004-19] WARN  eclipselink.logging.all - Exception [EclipseLink-5006] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.OptimisticLockException
Exception Description: The object [org.eclipse.kapua.service.device.registry.internal.DeviceImpl@1030ad36[tagIds={[]},groupId=<null>,clientId=B8:27:EB:59:53:C1,connectionId=8643563211773790169,connection=org.eclipse.kapua.service.device.registry.connection.internal.DeviceConnectionImpl@75d53125,status=ENABLED,displayName=Raspberry-Pi,lastEventId=8038133056394199237,lastEvent=org.eclipse.kapua.service.device.registry.event.internal.DeviceEventImpl@61798eaf,serialNumber=Raspberry-Pi,modelId=Raspberry-Pi,imei=<null>,imsi=<null>,iccid=<null>,biosVersion=N/A,firmwareVersion=N/A,osVersion=4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017,jvmVersion=25.65-b01 mixed mode,osgiFrameworkVersion=1.8.0,applicationFrameworkVersion=ESF_5.0.0,connectionInterface=eth0 (B8:27:EB:59:53:C1),connectionIp=192.168.2.6,applicationIdentifiers=W1,CONF-V1,CMD-V1,CERT-V1,DEPLOY-V2,ASSET-V1,VPNCLIENT-V1,PROV-V2,W1,heater,acceptEncoding=gzip,customAttribute1=<null>,customAttribute2=<null>,customAttribute3=<null>,customAttribute4=<null>,customAttribute5=<null>,modifiedOn=Wed Jan 24 13:44:49 UTC 2018,modifiedBy=1,optlock=116,attributes=<null>,properties=<null>,id=375671007149887232,scopeId=1,createdOn=Tue Jan 23 12:53:44 UTC 2018,createdBy=2]] cannot be updated because it has changed or been deleted since it was last read. 
Class> org.eclipse.kapua.service.device.registry.internal.DeviceImpl Primary Key> 375,671,007,149,887,232 
89315848 [qtp940060004-19] WARN  o.e.k.a.c.m.a.s.u.KapuaExceptionHandler - RPC service non-application error 
org.eclipse.kapua.KapuaOptimisticLockingException: The entity is out of state as it has been modified or deleted by another transaction.
at org.eclipse.kapua.commons.util.KapuaExceptionUtils.convertPersistenceException(KapuaExceptionUtils.java:53)
at org.eclipse.kapua.commons.jpa.EntityManagerSession.internalOnResult(EntityManagerSession.java:152)
at org.eclipse.kapua.commons.jpa.EntityManagerSession.onTransactedResult(EntityManagerSession.java:132)
at org.eclipse.kapua.service.device.registry.internal.DeviceRegistryServiceImpl.update(DeviceRegistryServiceImpl.java:83)
at org.eclipse.kapua.service.device.registry.internal.DeviceRegistryServiceImpl.update(DeviceRegistryServiceImpl.java:43)
at org.eclipse.kapua.service.device.registry.event.internal.DeviceEventServiceImpl.create(DeviceEventServiceImpl.java:93)
at org.eclipse.kapua.service.device.registry.event.internal.DeviceEventServiceImpl.create(DeviceEventServiceImpl.java:64)
at org.eclipse.kapua.service.device.registry.event.internal.DeviceEventServiceImpl.create(DeviceEventServiceImpl.java:40)
at org.eclipse.kapua.service.device.management.snapshot.internal.DeviceSnapshotManagementServiceImpl.lambda$get$0(DeviceSnapshotManagementServiceImpl.java:129)
at org.eclipse.kapua.commons.security.KapuaSecurityUtils.doPrivileged(KapuaSecurityUtils.java:110)
at org.eclipse.kapua.service.device.management.snapshot.internal.DeviceSnapshotManagementServiceImpl.get(DeviceSnapshotManagementServiceImpl.java:129)
at org.eclipse.kapua.app.console.module.device.server.GwtDeviceManagementServiceImpl.findDeviceSnapshots(GwtDeviceManagementServiceImpl.java:441)
at sun.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
at org.eclipse.kapua.app.console.core.filter.KapuaWebFilter.executeChain(KapuaWebFilter.java:43)
at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:564)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.OptimisticLockException: Exception [EclipseLink-5006] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.OptimisticLockException
Exception Description: The object [org.eclipse.kapua.service.device.registry.internal.DeviceImpl@1030ad36[tagIds={[]},groupId=<null>,clientId=B8:27:EB:59:53:C1,connectionId=8643563211773790169,connection=org.eclipse.kapua.service.device.registry.connection.internal.DeviceConnectionImpl@75d53125,status=ENABLED,displayName=Raspberry-Pi,lastEventId=8038133056394199237,lastEvent=org.eclipse.kapua.service.device.registry.event.internal.DeviceEventImpl@61798eaf,serialNumber=Raspberry-Pi,modelId=Raspberry-Pi,imei=<null>,imsi=<null>,iccid=<null>,biosVersion=N/A,firmwareVersion=N/A,osVersion=4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017,jvmVersion=25.65-b01 mixed mode,osgiFrameworkVersion=1.8.0,applicationFrameworkVersion=ESF_5.0.0,connectionInterface=eth0 (B8:27:EB:59:53:C1),connectionIp=192.168.2.6,applicationIdentifiers=W1,CONF-V1,CMD-V1,CERT-V1,DEPLOY-V2,ASSET-V1,VPNCLIENT-V1,PROV-V2,W1,heater,acceptEncoding=gzip,customAttribute1=<null>,customAttribute2=<null>,customAttribute3=<null>,customAttribute4=<null>,customAttribute5=<null>,modifiedOn=Wed Jan 24 13:44:49 UTC 2018,modifiedBy=1,optlock=116,attributes=<null>,properties=<null>,id=375671007149887232,scopeId=1,createdOn=Tue Jan 23 12:53:44 UTC 2018,createdBy=2]] cannot be updated because it has changed or been deleted since it was last read. 
Class> org.eclipse.kapua.service.device.registry.internal.DeviceImpl Primary Key> 375,671,007,149,887,232
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:876)
at org.eclipse.kapua.commons.jpa.EntityManager.flush(EntityManager.java:150)
at org.eclipse.kapua.commons.service.internal.ServiceDAO.update(ServiceDAO.java:224)
at org.eclipse.kapua.service.device.registry.internal.DeviceDAO.update(DeviceDAO.java:86)
at org.eclipse.kapua.service.device.registry.internal.DeviceRegistryServiceImpl.lambda$update$1(DeviceRegistryServiceImpl.java:116)
at org.eclipse.kapua.commons.jpa.EntityManagerSession.internalOnResult(EntityManagerSession.java:140)
... 63 common frames omitted
Caused by: org.eclipse.persistence.exceptions.OptimisticLockException: 
Exception Description: The object [org.eclipse.kapua.service.device.registry.internal.DeviceImpl@1030ad36[tagIds={[]},groupId=<null>,clientId=B8:27:EB:59:53:C1,connectionId=8643563211773790169,connection=org.eclipse.kapua.service.device.registry.connection.internal.DeviceConnectionImpl@75d53125,status=ENABLED,displayName=Raspberry-Pi,lastEventId=8038133056394199237,lastEvent=org.eclipse.kapua.service.device.registry.event.internal.DeviceEventImpl@61798eaf,serialNumber=Raspberry-Pi,modelId=Raspberry-Pi,imei=<null>,imsi=<null>,iccid=<null>,biosVersion=N/A,firmwareVersion=N/A,osVersion=4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017,jvmVersion=25.65-b01 mixed mode,osgiFrameworkVersion=1.8.0,applicationFrameworkVersion=ESF_5.0.0,connectionInterface=eth0 (B8:27:EB:59:53:C1),connectionIp=192.168.2.6,applicationIdentifiers=W1,CONF-V1,CMD-V1,CERT-V1,DEPLOY-V2,ASSET-V1,VPNCLIENT-V1,PROV-V2,W1,heater,acceptEncoding=gzip,customAttribute1=<null>,customAttribute2=<null>,customAttribute3=<null>,customAttribute4=<null>,customAttribute5=<null>,modifiedOn=Wed Jan 24 13:44:49 UTC 2018,modifiedBy=1,optlock=116,attributes=<null>,properties=<null>,id=375671007149887232,scopeId=1,createdOn=Tue Jan 23 12:53:44 UTC 2018,createdBy=2]] cannot be updated because it has changed or been deleted since it was last read. 
Class> org.eclipse.kapua.service.device.registry.internal.DeviceImpl Primary Key> 375,671,007,149,887,232
at org.eclipse.persistence.exceptions.OptimisticLockException.objectChangedSinceLastReadWhenUpdating(OptimisticLockException.java:144)
at org.eclipse.persistence.descriptors.VersionLockingPolicy.validateUpdate(VersionLockingPolicy.java:790)
at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.updateObjectForWriteWithChangeSet(DatabaseQueryMechanism.java:1086)
at org.eclipse.persistence.queries.UpdateObjectQuery.executeCommitWithChangeSet(UpdateObjectQuery.java:84)
at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:803)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1790)
at org.eclipse.persistence.internal.sessions.CommitManager.commitChangedObjectsForClassWithChangeSet(CommitManager.java:273)
at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:131)
at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4264)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1587)
at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:455)
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:874)
... 68 common frames omitted
```

**Comment by LeoNerdoG** [comment]
I have tried to reproduce this but could not do it (I tried with other packages too), so I am closing this.
