### ISSUE TITLE
KahaDB Message (ActiveMQ) store library throws an exception if Message property contains a not primitive object

### ISSUE THREAD

**Issue by riccardomodanese** [eclipse/kapua#164]
When the ActiveMQ Message property contains a not primitive object, the KahaDB store message library throws an exception (see below).
Anyway the KapuaSession cannot be stored inside incoming Message as reference since is not anymore available if the message processing happens after the client disconnection.

---------
2016-12-14 10:17:01,135 | TRACE | ActiveMQ NIO Worker 3 | org.apache.activemq.transport.mqtt.MQTTProtocolConverter | Error trace: {}
java.io.IOException: Object is not a primitive: org.eclipse.kapua.broker.core.plugin.ConnectorDescriptor@145af19f
    at org.apache.activemq.util.MarshallingSupport.marshalPrimitive(MarshallingSupport.java:156)[activemq-client-5.14.0.jar:5.14.0]
    at org.apache.activemq.util.MarshallingSupport.marshalPrimitiveMap(MarshallingSupport.java:64)[activemq-client-5.14.0.jar:5.14.0]
    at org.apache.activemq.command.Message.beforeMarshall(Message.java:241)[activemq-client-5.14.0.jar:5.14.0]
    at org.apache.activemq.store.kahadb.KahaDBStore$KahaDBMessageStore.asyncAddQueueMessage(KahaDBStore.java:387)[activemq-kahadb-store-5.14.0.jar:5.14.0]
    at org.apache.activemq.store.kahadb.KahaDBTransactionStore.asyncAddQueueMessage(KahaDBTransactionStore.java:423)[activemq-kahadb-store-5.14.0.jar:5.14.0]

**Comment by riccardomodanese** [comment]
This issue will be addressed by the elasticsearch rest client refactoring pr.

**Comment by riccardomodanese** [comment]
pr #503 should solve the issue and also address #440
