### ISSUE TITLE
subscribe to a topic 

### ISSUE THREAD

**Issue by aycanvargun** [eclipse/kapua#2199]
Hi, 

I am trying to connect to Kapua and subscribe to a topic, then to read the data. But I have errors on my Broker. user123 is admin. With the same user I can publish data from a different client. But, I am not able to subscribe to the topic I created from another device. Where am i wrong? 

**My code is:**

```
public void function () throws Exception {
    try (Client client = KuraMqttProfile.newProfile(FuseClient.Builder::new)
            .accountName("acme123")
            .clientId(" client-2")
            .brokerUrl("tcp://10.254.143.142:11883")
            .credentials(userAndPassword("user123", "Kapua@12345678"))
            .build()) {

        Application application = client.buildApplication("app1").build();

        waitForConnection(application.transport());
        application.data(Topic.of("my", "sender")).subscribe(message -> {
            System.out.format("Received: %s%n", message);
        });

        Thread.sleep(1000);

    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```

**The logs are:** 

```

10:30:57.936 [ActiveMQ NIO Worker 3] INFO  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User name user123 - client id:  client-2, connection id: ID:cd52fa1cacda-36669-1542481844119-5:1134
10:30:58.568 [ActiveMQ NIO Worker 3] INFO  o.e.k.s.a.s.AuthenticationServiceShiroImpl - Login for thread '163' - 'ActiveMQ NIO Worker 3' - 'org.apache.shiro.subject.support.DelegatingSubject@39fb5839'
10:31:03.003 [Camel (camelContext) thread #1 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  eclipselink.logging.all - Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "UC_CLIENTID_INDEX_D ON KAPUADB.DVC_DEVICE(SCOPE_ID, CLIENT_ID) VALUES (8539744234403289497, ' client-2', 5680765385457641386)"; SQL statement:
INSERT INTO dvc_device (accept_encoding, app_framework_version, app_identifiers, attributes, bios_version, client_id, connection_interface, connection_ip, created_on, custom_attribute_1, custom_attribute_2, custom_attribute_3, custom_attribute_4, custom_attribute_5, display_name, firmware_version, iccid, imei, imsi, jvm_version, model_id, modified_on, optlock, os_version, osgi_framework_version, properties, serial_number, status, connection_id, created_by, group_id, id, last_event_id, modified_by, scope_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-193]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        ...


Error Code: 23505
Call: INSERT INTO dvc_device (accept_encoding, app_framework_version, app_identifiers, attributes, bios_version, client_id, connection_interface, connection_ip, created_on, custom_attribute_1, custom_attribute_2, custom_attribute_3, custom_attribute_4, custom_attribute_5, display_name, firmware_version, iccid, imei, imsi, jvm_version, model_id, modified_on, optlock, os_version, osgi_framework_version, properties, serial_number, status, connection_id, created_by, group_id, id, last_event_id, modified_by, scope_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [null, null, app1, null, null,  client-2, null, null, 2018-11-22 10:31:03.007, null, null, null, null, null, null, null, null, null, null, 1.8.0_181, null, 2018-11-22 10:31:03.007, 1, 10.0, null, null, null, ENABLED, 3875301070498958418, 917791760301272189, null, 8991453457628099758, null, 917791760301272189, 8539744234403289497]
Query: InsertObjectQuery(org.eclipse.kapua.service.device.registry.internal.DeviceImpl@1116f190[tagIds={[]},groupId=<null>,clientId= client-2,connectionId=3875301070498958418,connection=<null>,status=ENABLED,displayName=<null>,lastEventId=<null>,lastEvent=<null>,serialNumber=<null>,modelId=<null>,imei=<null>,imsi=<null>,iccid=<null>,biosVersion=<null>,firmwareVersion=<null>,osVersion=10.0,jvmVersion=1.8.0_181,osgiFrameworkVersion=<null>,applicationFrameworkVersion=<null>,connectionInterface=<null>,connectionIp=<null>,applicationIdentifiers=app1,acceptEncoding=<null>,customAttribute1=<null>,customAttribute2=<null>,customAttribute3=<null>,customAttribute4=<null>,customAttribute5=<null>,modifiedOn=Thu Nov 22 10:31:03 UTC 2018,modifiedBy=917791760301272189,optlock=1,attributes=<null>,properties=<null>,id=8991453457628099758,scopeId=8539744234403289497,createdOn=Thu Nov 22 10:31:03 UTC 2018,createdBy=917791760301272189])
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:331)
     ...
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "UC_CLIENTID_INDEX_D ON KAPUADB.DVC_DEVICE(SCOPE_ID, CLIENT_ID) VALUES (8539744234403289497, ' client-2', 5680765385457641386)"; SQL statement:
INSERT INTO dvc_device (accept_encoding, app_framework_version, app_identifiers, attributes, bios_version, client_id, connection_interface, connection_ip, created_on, custom_attribute_1, custom_attribute_2, custom_attribute_3, custom_attribute_4, custom_attribute_5, display_name, firmware_version, iccid, imei, imsi, jvm_version, model_id, modified_on, optlock, os_version, osgi_framework_version, properties, serial_number, status, connection_id, created_by, group_id, id, last_event_id, modified_by, scope_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-192]
        at org.h2.engine.SessionRemote.done(SessionRemote.java:624)
...
10:31:48.265 [ActiveMQ NIO Worker 2] WARN  o.e.k.b.c.p.KapuaSecurityBrokerFilter - User user123 ( client-2 - tcp://217.78.106.69:59549 - conn id 3875301070498958418) is not authorized to read from: Consumer.8,539,744,234,403,289,497: client-2:AT_LEAST_ONCE.VirtualTopic.acme123. client-2.app1.my.sender
10:31:48.265 [ActiveMQ NIO Worker 2] WARN  o.a.a.b.TransportConnection.Service - Security Error occurred on connection to: tcp://217.78.106.69:59549, User user123 ( client-2 - tcp://217.78.106.69:59549 - conn id 3875301070498958418) is not authorized to read from: Consumer.8,539,744,234,403,289,497: client-2:AT_LEAST_ONCE.VirtualTopic.acme123. client-2.app1.my.sender
10:31:48.266 [ActiveMQ NIO Worker 2] WARN  o.a.a.t.m.s.AbstractMQTTSubscriptionStrategy - Error subscribing to acme123/ client-2/app1/my/sender
java.lang.SecurityException: User user123 ( client-2 - tcp://217.78.106.69:59549 - conn id 3875301070498958418) is not authorized to read from: Consumer.8,539,744,234,403,289,497: client-2:AT_LEAST_ONCE.VirtualTopic.acme123. client-2.app1.my.sender
        at org.eclipse.kapua.broker.core.plugin.KapuaSecurityBrokerFilter.internalAddConsumer(KapuaSecurityBrokerFilter.java:642)

```

**Comment by Coduz** [comment]
Hi @aycanvargun , 

I've edited your issue to improve readability.

First thing is that the log has some errors, but if the connection is successful for both clients, those errors does not relate to the publish/subscribe problem you are having.

Second I don't see the `publish` code. Am I missing something? 

Then , May I ask you which version of Kapua are you using? 

As a general note, Devices connected with a user that has only `broker:connect` are allowed to publish and subscribe only to topics that include the account name and their client id. 
i.e:
- `/myAccountName/myClientId/#` for telemetry messages
- `$EDC/myAccountName/myClientId/#` for control messages.

To allow cross-client communication more permission assigned to the user used are required. 
Additional permission required are:
- `data:manage` to allow telemetry messages exchange
- `device:manage` to allow control messages exchange

Regards, 

_Alberto_

**Comment by aycanvargun** [comment]
Hi @Coduz , 

I also tried with kapua-broker username and its password, but i have the same  error. In fact,  my purpose is  `foo-bar-1` client to be able to take command messages from my other client `foo-bar-2` or from a Kapua REST API client.  I am using Kapua 1.0.0. I deployed it as Docker containers. My code with publisher part and broker username+password is

	public  void function() throws Exception {

        try (final Client client = KuraMqttProfile.newProfile(FuseClient.Builder::new)
                .accountName("kapua-sys")
                .clientId("foo-bar-1")
                .brokerUrl("tcp://10.254.143.142:11883")
                .credentials(userAndPassword("kapua-broker", "kapua-password"))
                .build()) {
				  
        	   try (final Application application = client.buildApplication("app1").build()) {

                   // wait for connection
                    waitForConnection(application.transport());
                   
                   application.data(Topic.of("my", "topic")).subscribe(message -> {
                       System.out.format("Received: %s%n", message);
                   });
                   
                   Sender<RuntimeException> sender = application
     				      .data(Topic.of("my", "topic"))
     				      .errors(ignore());
                  
                   while (true) {
				    	 
				      // send
				      sender.send(Payload.of("counter", 996));
				      try {
						Thread.sleep(1000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				    }
			  
			 						    				  									 
		}
		catch (InterruptedException e) {
			e.printStackTrace();
	}	
}
}

How can I create a user with this permissions?
data:manage to allow telemetry messages exchange
device:manage to allow control messages exchange

**Comment by Coduz** [comment]
Hi @aycanvargun ,

The current error is that clientId `foo-bar-1` cannot subscribe to `kapua-sys/foo-bar-1/app1/my/receiver` due to permission problems. 

Topics, clientId, account name seems fine.

Could you please try with `kapua-sys` as a user used to establish the connection? 

Regards ,

_Alberto_

**Comment by Coduz** [comment]
Hi @aycanvargun ,

I'll close this due to inactivity. 

Feel free to reopen this issue or create a new one if you need more help.

Regards,

_Alberto_
