### ISSUE TITLE
Is Open Shift mandatory for SSO?

### ISSUE THREAD

**Issue by drasko** [eclipse/kapua#2536]
Here: https://github.com/eclipse/kapua/tree/develop/deployment/openshift/sso is noted that we need OpenShift for SSO. Is it possible to use Kapua SSO without OpenShif - for example in native deployment or Kubernetes?

I can see that Keycloak is used, our idea is to use [Dex](https://github.com/dexidp/dex) nad OpenLDAP instead. Our deployment is done in Kubernets, or we deploy individual containers via docker-compose, and we do not use OpenShift.

**Comment by lorthirk** [comment]
Hi @drasko,

AFAIK OpenShift is not mandatory for SSO. However, SSO implementation in Kapua is not yet mature. One thing I can think about for sure is that you don't have a way to specify the account for the user the logs in via SSO.

**Comment by mteodor** [comment]
can you paste me an example as a reference, thanks

**Comment by manuraf** [comment]
I'm trying to configure SSO with keycloak and starting all containes. I set **sso.provider** and **sso.openid.client.id** in console/web/../resources/console-setting.properties but nothing change, SSO is not enabled.

**Comment by lorthirk** [comment]
Also look for `console.sso.*` in [console/web/src/main/resources/console-setting.properties](https://github.com/eclipse/kapua/blob/develop/console/web/src/main/resources/console-setting.properties)

**Comment by mteodor** [comment]
if you change console-setting.properties you need to rebuild docker image, right?
I understood that your suggestion was to pass it as system properties in docker-compose file?

**Comment by lorthirk** [comment]
Yes, if you change `console-setting.properties` you have to rebuild the container. 

Another easier way, however, would be to redefine the `JAVA_OPTS` environment variable, originally defined in the Dockerfile of the Console, and extending it with the properties coming from `console-setting.properties` with appropriate values.

Unfortunately, as I said, the SSO implementation is not yet mature, and for sure such confusion about the OpenShift vs. Docker way to activate it doesn't help. We're for sure open to any contribution about it, and I recall at least one open discussion about sso at https://github.com/eclipse/kapua/issues/481, so resuming that one in order to have a clear path to implement it is a welcome contribution as well.

**Comment by mteodor** [comment]
I'm failing to build kapua
I followed steps here
https://www.eclipse.org/kapua/docs/1.0.0/developer-guide/en/building.html
But I get following error

```ARNING] The requested profile "dev" could not be activated because it does not exist.                                                                                                                                              
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project kapua-service-api: Compilation failure: Compilation failure:                                                
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/query/KapuaQuery.java:[24,33] package javax.xml.bind.annotation does not exist                                                                           
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/query/KapuaQuery.java:[25,33] package javax.xml.bind.annotation does not exist                                                                           
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/query/KapuaQuery.java:[26,33] package javax.xml.bind.annotation does not exist                                                                           
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/query/KapuaQuery.java:[27,42] package javax.xml.bind.annotation.adapters does not exist                                                                  
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java:[20,33] package javax.xml.bind.annotation does not exist                                                                                
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java:[21,33] package javax.xml.bind.annotation does not exist                                                                                
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java:[22,33] package javax.xml.bind.annotation does not exist                                                                                
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java:[23,42] package javax.xml.bind.annotation.adapters does not exist                                                                       
[ERROR] /home/mirko/kapua/service/api/src/main/java/org/eclipse/kapua/model/KapuaEntity.java:[33,2] cannot find symbo```

**Comment by lorthirk** [comment]
Which JDK versions have you installed on your system?

**Comment by mteodor** [comment]
java --version
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by lorthirk** [comment]
I see. You need JDK 8 in order to build Kapua; JDK 11 is not currently supported.

**Comment by mteodor** [comment]
OK, i've built project with JDK 8, but need more help. I was following instructions on dev guide.
But now I'm having a problem that my changes to java files  and Dockerfile are not reflected to the docker images. 

Is this the file that is used for building console docker?
kapua/assembly/console/docker/Dockerfile
I was changing it and nothing, writing garbage into it but building docker didn't complain

Also I've added some printing to ConsoleListener with LOG.info but nothing is coming into docker logs although initial message with `        LOG.info("Initialize Console JABContext JABContext Provider");` is printed

**Comment by lorthirk** [comment]
Have you followed [this instructions](https://github.com/eclipse/kapua/blob/develop/docs/developer-guide/en/running.md#docker-containers) to build the Docker images?

**Comment by mteodor** [comment]
yes, exact these steps
```Before running Kapua on Docker, you need to

Install docker
Run mvn -f assembly -Pdocker once to build containers
Now, you can start Kapua by using Docker Compose. To do so, run

kapua/deployments/docker/docker-deploy.sh

**Comment by lorthirk** [comment]
I see. 

Please, since we're going off topic here, check if you have Kapua running when you're building containers: if the image you're going to build is running inside a container Docker will not build the new one. Should you still have any issue, please open a new issue so we can focus on that one. Thank you!

**Comment by mteodor** [comment]
no image, no container running, I was running docker system prune numerous times

**Comment by lorthirk** [comment]
Please open a new issue about this. Thanks!

**Comment by mteodor** [comment]
I'm getting this error after I've configured sso
```
656889 [qtp913190639-18] WARN  o.e.j.s.handler.ContextHandler.root - Exception while dispatching incoming RPC call 
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.lang.String org.eclipse.kapua.app.console.core.shared.service.GwtSettingsService.getSsoLoginUri()' threw an unexpected exception: java.lang.
IllegalStateException: Unable to lookup SSO redirect URL
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:385)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:588)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```


```
ENV JAVA_OPTS "-Dcommons.db.schema.update=false \
               -Dcommons.db.connection.host=\${SQL_DB_ADDR} \
               -Dcommons.db.connection.port=\${SQL_DB_PORT} \
               -Dbroker.host=\${BROKER_ADDR} \
               -Ddatastore.elasticsearch.nodes=\${DATASTORE_ADDR} \
               -Ddatastore.elasticsearch.port=\${DATASTORE_PORT} \
               -Ddatastore.client.class=\${DATASTORE_CLIENT} \
               -Dcommons.eventbus.url=\${SERVICE_BROKER_ADDR} \
               -Dcertificate.jwt.private.key=file:///var/opt/jetty/key.pk8 \
               -Dcertificate.jwt.certificate=file:///var/opt/jetty/cert.pem \
               -Dsso.provider=generic \
               -Dsso.openid.client.id=@!xxxxxxxxxxxxxxxxxxxxxxxxxxxx4 \
               -Dsso.openid.client.secret=xxxxxxxxxxxxxxxxxxxxx \
               -Dsso.site.home.uri=http://138.68.107.142:8080 \
               -Dsso.openid.redirect.uri=http://138.68.107.142:8080/sso/callback \
               -Dsso.sso.generic.openid.server.endpoint.auth=https://gluu-auth.tk/oxauth/restv1/authorize \
               -Dsso.generic.openid.server.endpoint.token=https://gluu-auth.tk/oxauth/restv1/token"

```

**Comment by mteodor** [comment]
this looks like an error or am I missing something
https://github.com/eclipse/kapua/blob/1.0.0/console/core/src/main/java/org/eclipse/kapua/app/console/core/server/GwtSettingsServiceImpl.java#L44

**Comment by mteodor** [comment]
Hi @lorthirk , I'm getting this error in the log
```
9B0.990E.3051.CA54&state=6f83eade-8fb1-45f1-8aec-12c500272a0a&redirect_uri=http%3A%2F%2Fportal.solidsense.tk%3A8080%2Fsso%2Fcallback
163601 [qtp913190639-10] WARN  o.eclipse.jetty.server.HttpChannel - /sso/callback javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
```
where is the right place to import the https certificate of my server?

**Comment by mteodor** [comment]
latest error I'm getting, 
after obtainging the access token from auth server token endpoint
do you know what is the problem here ?


```
      at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.shiro.authc.AuthenticationException: org.apache.shiro.ShiroException: Failed to parse JWT
        at org.eclipse.kapua.service.authentication.shiro.KapuaAuthenticator.doMultiRealmAuthentication(KapuaAuthenticator.java:85)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269)
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
        at org.eclipse.kapua.service.authentication.shiro.AuthenticationServiceShiroImpl.login(AuthenticationServiceShiroImpl.java:145)


        ... 57 common frames omitted
Caused by: org.apache.shiro.ShiroException: Failed to parse JWT
        at org.eclipse.kapua.service.authentication.shiro.realm.JwtAuthenticatingRealm.extractExternalId(JwtAuthenticatingRealm.java:194)
        at org.eclipse.kapua.service.authentication.shiro.realm.JwtAuthenticatingRealm.doGetAuthenticationInfo(JwtAuthenticatingRealm.java:113)
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568)
        at org.eclipse.kapua.service.authentication.shiro.KapuaAuthenticator.doMultiRealmAuthentication(KapuaAuthenticator.java:58)
        ... 63 common frames omitted
Caused by: org.jose4j.jwt.consumer.InvalidJwtException: Unable to process JOSE object (cause: org.jose4j.lang.JoseException: Invalid JOSE Compact Serialization. Expecting either 3 or 5 parts for JWS or JWE respectively but was 1.): 1ca45681-c994-4068-98e9-50f15ea7718d
        at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:375)
        at org.eclipse.kapua.sso.jwt.JwtProcessor.extractIssuer(JwtProcessor.java:124)
        at org.eclipse.kapua.sso.jwt.JwtProcessor.process(JwtProcessor.java:103)
        at org.eclipse.kapua.service.authentication.shiro.realm.JwtAuthenticatingRealm.extractExternalId(JwtAuthenticatingRealm.java:191)
        ... 66 common frames omitted
Caused by: org.jose4j.lang.JoseException: Invalid JOSE Compact Serialization. Expecting either 3 or 5 parts for JWS or JWE respectively but was 1.
        at org.jose4j.jwx.JsonWebStructure.fromCompactSerialization(JsonWebStructure.java:85)
        at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:291)
        ... 69 common frames omitted
11:31:30.113 [qtp913190639-19] ERROR o.e.k.a.c.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /manager/html - Error: Not Found
12:08:20.967 [qtp913190639-18] ERROR o.e.k.a.c.c.s.KapuaErrorHandlerServlet - Processed HTTP error! Code: 404 - Request: /manager/html - Error: Not Found

**Comment by lorthirk** [comment]
Shiro is unable to parse the JWT you're trying to send. Unfortunately, without any information on your code, it's pretty hard to understand what is actually going on.

**Comment by mteodor** [comment]
ok, i've sorted that out and now it seems that it succefully authenticates ( at least that is in the log)

```
20:55:29.545 [qtp913190639-14] INFO  o.e.k.a.c.c.s.GwtAuthorizationServiceImpl - >>> THIS IS INFO <<<
20:55:29.546 [qtp913190639-14] WARN  o.e.k.a.c.c.s.GwtAuthorizationServiceImpl - >>> THIS IS WARN <<<
20:55:29.546 [qtp913190639-14] INFO  o.e.k.s.a.s.AuthenticationServiceShiroImpl - Shiro global session timeout set to indefinite.
20:55:29.546 [qtp913190639-14] INFO  o.e.k.s.a.s.AuthenticationServiceShiroImpl - Shiro global session validator scheduler disabled.
20:55:30.102 [qtp913190639-14] INFO  eclipselink.logging.all - EclipseLink, version: Eclipse Persistence Services - 2.6.3.v20160428-59c81c5
20:55:30.236 [qtp913190639-14] INFO  eclipselink.logging.connection - /file:/var/opt/jetty/webapps/root/WEB-INF/lib/kapua-user-internal-1.1.0-SNAPSHOT.jar_kapua-user login successful
20:55:31.116 [qtp913190639-14] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US
```

but it doesnt let me in, I'm getting login page again after the whole login sequence, any hints?

**Comment by mteodor** [comment]
@lorthirk after succesfull login what should happen?

**Comment by lorthirk** [comment]
Keycloak should redirect to the Kapua home page passing the SSO Token as a query parameter; the homepage should recognize it and log the user automatically in the root account

**Comment by mteodor** [comment]
I've received authorization token on the Kapua  sso/callback and I've received access token from authentication server and kapua logs report successful login ( as you can see in the log snippet) but homepage doesn't open

**Comment by lorthirk** [comment]
Again, we're going out of topic here. Please open a new issue.

**Comment by drasko** [comment]
@lorthirk this seems directly related to SSO - i.e. even though it receives a valid token from the gateway, Kapua does not proceed to home page but gets stucked on login screen. I see it as SSO rmalfunction.

**Comment by lorthirk** [comment]
@drasko sure, no doubts about this :) but it's not at all related to OpenShift and the original question IMHO.

**Comment by drasko** [comment]
Ah, I see - there is OpenShift in the title, and so on... Yes, confusing. Let's open a new issue, SSO-only related.

**Comment by mteodor** [comment]
here is the new one
https://github.com/eclipse/kapua/issues/2566
