### ISSUE TITLE
REST API Call when using SSO

### ISSUE THREAD

**Issue by mteodor** [eclipse/kapua#2601]
Hi,
I've configured kapua to authenticate against keycloak.
Also I have SPA which authenticates against same keycloak instance.
How can I call kapua REST API from my SPA?

**Comment by mteodor** [comment]
@lorthirk any hint on this?

**Comment by lorthirk** [comment]
Hi @mteodor,

Are you able to obtain the JWT coming from Keyclocak somehow?

**Comment by mteodor** [comment]
Yes, I'm using implicit flow for SPA, so I get access token from keycloak

**Comment by lorthirk** [comment]
So you should be able to use that token to authenticate in the `authentication/jwt` endpoint. The response will contain another JWT, this time issued by Kapua, that can be used as a bearer in the `Authorization` HTTP header.

**Comment by mteodor** [comment]
super great, thanks a lot

**Comment by mteodor** [comment]
@lorthirk is this the right way to pass the access token
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"jwt":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFWFRpeVBIWXRaRnV0N1JwOWJLZTl0R2ktSnFXMF9MR1hUR2ctZURDR2o0In0.eyJqdGkiOiJkYzVjNjBiZS1lNTkwLTQ3ZDEtYTczMS00Yzc1ZmNkY2IyZmQiLCJleHAiOjE1NTg0NDY1NDgsIm5iZiI6MCwiaWF0IjoxNTU4NDQ1NjQ4LCJpc3MiOiJodHRwOi8vYXV0aC5zb2xpZHNlbnNlLnRrL2F1dGgvcmVhbG1zL2thcHVhIiwiYXVkIjoiY29uc29sZSIsInN1YiI6ImViYzE0OTZkLTVmYTYtNDE5OC05OWRmLTMwYzcyOTYzNGU4YyIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNvbnNvbGUiLCJub25jZSI6ImQ0MWUyYjhmY2Q1MTQyYjM5YWNjNTJjMTJhZmZhY2NkIiwiYXV0aF90aW1lIjoxNTU4NDQ1NjQ4LCJzZXNzaW9uX3N0YXRlIjoiOGQ2MDEwMzYtZDgzNS00ZDZlLTgyNmYtYzJhM2JhZjRkMzhiIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vcG9ydGFsLnNvbGlkc2Vuc2UudGsiLCJodHRwOi8va2FwdWEuc29saWRzZW5zZS50ayIsImh0dHA6Ly91aS5tZW5kZXIuY29tIiwiaHR0cDovL21lbmRlci5zb2xpZHNlbnNlLnRrIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sIm5hbWUiOiJEcmFza28gRHJhc2tvdmljIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZHJhc2tvIiwiZ2l2ZW5fbmFtZSI6IkRyYXNrbyIsImZhbWlseV9uYW1lIjoiRHJhc2tvdmljIiwiZW1haWwiOiJkcmFza29AbWFpbmZsdXguY29tIn0.NHQnizb9PFVYvnQ8eD4ojDvNl2TNGPSSqq7_4TyXf1VLMbAI8ZGzCuUtvmflk7auyEDy5ex5nn8hac2jGhwIIumDO5E90WSxQPK-aqcGjOHYHGFzKopeGYmAg0lC-EN9h7MzQcIchc7ikX91TW50OsZDTXbqWY9tj0XvAXX5ggD4PkbIURvgRCuk7BRUJRHL5NMH_D_HEQCzD4aHnj7p4DgYOHwryNwTAUo0gB4ZNFhmMbA3ncExkCfvXMFhesYGSIVu-e7nY3UrTB_kqe9AtgMFGknkKBTGLQKMDrFxAFP-nFMSOzOTi2uSqZxytcN1kNLuLVzGj854Hr15pIJ66Q"}' 'http://kapua.solidsense.tk/v1/authentication/jwt' ```

**Comment by lorthirk** [comment]
Yes, that should be correct.

**Comment by mteodor** [comment]
this should work right?
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/html' -d '{
  "password": "kapua-sys",
  "username": "kapua-password"
}' 'http://kapua.solidsense.tk:8081/v1/authentication/user'
```

```{"httpErrorCode":500,"message":"HTTP 406 Not Acceptable"}```


```
javax.ws.rs.NotAcceptableException: HTTP 406 Not Acceptable
        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.getMethodRouter(MethodSelectingRouter.java:529)
        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.access-zsh(MethodSelectingRouter.java:94)
        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.apply(MethodSelectingRouter.java:779)
        at org.glassfish.jersey.server.internal.routing.MethodSelectingRouter.apply(MethodSelectingRouter.java:371)
        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
        at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
        at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
        at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
        at org.glassfish.jersey.server.ServerRuntime.run(ServerRuntime.java:318)
        at org.glassfish.jersey.internal.Errors.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler.doFilter(ServletHandler.java:1655)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
        at org.eclipse.jetty.servlet.ServletHandler.doFilter(ServletHandler.java:1642)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.eclipse.jetty.servlet.ServletHandler.doFilter(ServletHandler.java:1634)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lorthirk** [comment]
No, as you can see the server responds `406 Not Acceptable` because you're asking for a `text/html` content type while the server can only reply in `application/json` and `application/xml`. So, in order to get a successful reply, you either have to specify `application/json` or `application/xml` instead of `text/html` as the value of the `Accept` header.

**Comment by mteodor** [comment]
Ok, thanks

**Comment by mteodor** [comment]
@lorthirk is there anything that i need to set additionally for api to be called from my SPA I'm having problem with CORS, I dont have CORS headers in response from kapua

**Comment by lorthirk** [comment]
No, CORS headers should be automatically set for every REST call. I just tried in a local installation, and I can correctly see them:
```
Access-Control-Allow-Origin →*
Access-Control-Allow-Methods →GET, POST, DELETE, PUT
Access-Control-Allow-Headers →X-Requested-With, Content-Type, Authorization
```
Are you sure your SPA is not dropping them somehow?

**Comment by Coduz** [comment]
Closing for inactivity.
Feel free to reopen if you need it.
