### ISSUE TITLE
Broker does no handle "wrong" data gracefully

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#266]
When a device is successfully connected to the broker (authentication "ok") but still sends data unexpected by the broker, then the broker currently just drops the message with an exception in the log:

```
12:47:07,321 [Camel (camelContext) thread #7 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  ErrorMessageListener:92  - Exception: 
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.eclipse.kapua.service.device.call.message.kura.lifecycle.KuraBirthPayload.getUptime(KuraBirthPayload.java:209)
	at org.eclipse.kapua.translator.kura.kapua.TranslatorLifeBirthKuraKapua.translate(TranslatorLifeBirthKuraKapua.java:83)
	at org.eclipse.kapua.translator.kura.kapua.TranslatorLifeBirthKuraKapua.translate(TranslatorLifeBirthKuraKapua.java:46)
	at org.eclipse.kapua.translator.kura.kapua.TranslatorLifeBirthKuraKapua.translate(TranslatorLifeBirthKuraKapua.java:39)
	at org.eclipse.kapua.broker.core.message.JmsUtil.convertToKapuaMessage(JmsUtil.java:194)
	at org.eclipse.kapua.broker.core.message.JmsUtil.convertToCamelKapuaMessage(JmsUtil.java:159)
	at org.eclipse.kapua.broker.core.converter.AbstractKapuaConverter.convertTo(AbstractKapuaConverter.java:85)
	at org.eclipse.kapua.broker.core.converter.KapuaLifeCycleConverter.convertToBirth(KapuaLifeCycleConverter.java:78)
…
```

I would expect such messages to still pop up in the "events" tab of the device, but with some failure indication.

**Comment by Coduz** [comment]
We can make this in a way that `DeviceEvent`s can have a raw body in which we can store raw bodies (like we currently do with the DataMessages)
