### ISSUE TITLE
ActiveMQ not starting because of Liquibase error

### ISSUE THREAD

**Issue by lorthirk** [eclipse/kapua#329]
Hello everyone,

I just pulled the latest commits from `develop` (last commit b99b524feb7b1125726270f5d5162996b97b23fe) but now ActiveMQ crashes at startup on my develop Vagrant machine. Here's the log:

```
2017-02-28 11:39:14,223 | INFO  | main | org.apache.camel.spring.SpringCamelContext | Route: route1 started and consuming from: Endpoint[activemq://queue:Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E?acknowledgementModeName=CLIENT_ACKNOWLEDGE&asyncConsumer=false&concurrentConsumers=10&maxConcurrentConsumers=10&transacted=false]
2017-02-28 11:39:14,224 | INFO  | main | org.apache.camel.spring.SpringCamelContext | Total 1 routes, of which 1 is started.
2017-02-28 11:39:14,245 | INFO  | main | org.apache.camel.spring.SpringCamelContext | Apache Camel 2.16.3 (CamelContext: camelContext) started in 0.854 seconds
2017-02-28 11:39:14,254 | WARN  | main | org.apache.activemq.broker.BrokerService | Memory Usage for the Broker (6144mb) is more than the maximum available for the JVM: 989 mb - resetting to 70% of maximum available: 692 mb
2017-02-28 11:39:14,255 | INFO  | main | org.apache.activemq.broker.BrokerService | Using Persistence Adapter: KahaDBPersistenceAdapter[/usr/local/activemq/apache-activemq-5.14.0/data/kahadb]
2017-02-28 11:39:16,181 | INFO  | main | org.apache.activemq.store.kahadb.plist.PListStoreImpl | PListStore:[/usr/local/activemq/apache-activemq-5.14.0/data/kapua/tmp_storage] started
2017-02-28 11:39:16,301 | INFO  | main | org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin | >> installPlugin org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin
2017-02-28 11:39:16,710 | INFO  | main | org.reflections.Reflections | Reflections took 92 ms to scan 5 urls, producing 725 keys and 728 values 
2017-02-28 11:39:18,373 | ERROR | main | org.apache.activemq.broker.BrokerService | Failed to start Apache ActiveMQ ([kapua, null], java.lang.RuntimeException: liquibase.exception.LockException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): Not enough rights for object "PUBLIC.DATABASECHANGELOGLOCK"; SQL statement:
CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)) [90096-192])
2017-02-28 11:39:18,383 | INFO  | main | org.apache.activemq.broker.BrokerService | Apache ActiveMQ 5.14.0 (kapua, null) is shutting down
2017-02-28 11:39:18,387 | INFO  | main | org.apache.activemq.broker.TransportConnector | Connector mqtt stopped
2017-02-28 11:39:18,393 | INFO  | main | org.apache.activemq.broker.TransportConnector | Connector mqtts stopped
2017-02-28 11:39:18,394 | INFO  | main | org.apache.activemq.broker.TransportConnector | Connector tcp stopped
2017-02-28 11:39:18,394 | INFO  | main | org.apache.activemq.broker.TransportConnector | Connector ws stopped
2017-02-28 11:39:18,395 | INFO  | main | org.apache.activemq.store.kahadb.plist.PListStoreImpl | PListStore:[/usr/local/activemq/apache-activemq-5.14.0/data/kapua/tmp_storage] stopped
2017-02-28 11:39:18,396 | INFO  | main | org.apache.activemq.store.kahadb.KahaDBStore | Stopping async queue tasks
2017-02-28 11:39:18,397 | INFO  | main | org.apache.activemq.store.kahadb.KahaDBStore | Stopping async topic tasks
2017-02-28 11:39:18,398 | INFO  | main | org.apache.activemq.store.kahadb.KahaDBStore | Stopped KahaDB
2017-02-28 11:39:18,441 | INFO  | main | org.apache.activemq.broker.BrokerService | Apache ActiveMQ 5.14.0 (kapua, null) uptime 4.194 seconds
2017-02-28 11:39:18,442 | INFO  | main | org.apache.activemq.broker.BrokerService | Apache ActiveMQ 5.14.0 (kapua, null) is shutdown
```

Rolling back to a74ebefd23e6170ab1c73a5d001ae5404b5cb53c apparently fixes it

@hekonsek does it sounds familiar to you maybe?

**Comment by hekonsek** [comment]
This [1] code is responsible for applying schema to database. Any idea why your credentials are not enough to modify a schema?

[1] https://github.com/eclipse/kapua/blob/7d01366a863a106fd1b0632568c9b24ccf1d48ee/broker-core/src/main/java/org/eclipse/kapua/broker/core/KapuaBrokerSecurityPlugin.java#L55-L58

**Comment by lorthirk** [comment]
Honestly not. I added some logging lines to check that the values are correctly read, and indeed they are, but the error still persist:

```
2017-02-28 15:20:45,006 | INFO  | main | org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin | >> installPlugin org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin
2017-02-28 15:20:45,154 | INFO  | main | org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin | >> BrokerPlugin username: kapua
2017-02-28 15:20:45,154 | INFO  | main | org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin | >> BrokerPlugin password: kapua
2017-02-28 15:20:45,155 | INFO  | main | org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin | >> BrokerPlugin jdbc url: jdbc:h2:tcp://192.168.33.10:3306/kapuadb;schema=kapuadb
2017-02-28 15:20:45,404 | INFO  | main | org.reflections.Reflections | Reflections took 71 ms to scan 5 urls, producing 725 keys and 728 values 
2017-02-28 15:20:49,427 | ERROR | main | org.apache.activemq.broker.BrokerService | Failed to start Apache ActiveMQ ([kapua, null], java.lang.RuntimeException: liquibase.exception.LockException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): Not enough rights for object "PUBLIC.DATABASECHANGELOGLOCK"; SQL statement:
CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)) [90096-192])
2017-02-28 15:20:49,436 | INFO  | main | org.apache.activemq.broker.BrokerService | Apache ActiveMQ 5.14.0 (kapua, null) is shutting down
```

**Comment by ctron** [comment]
It works fine with the docker images. So it must have something to do with the vagrant setup, I would assume.

**Comment by stefanomorson** [comment]
Hi all,

from what I see, Liquibase is trying to create a table in the "PUBLIC" schema which is the H2 default. 
Kapua persistence is supposed to work with a configurable schema name that is defined in the file named "kapua-environment-setting.properties". For example the property is used to create the JPA's EntityManagerFactories.

@hekonsek : I think it should be fairly possible to manage this in Liquibase, right ?

**Comment by BcGovBrian** [comment]
Hi all,

I'm seeing a similar but slightly different issue in OpenShift.

I've built and deployed an image to OpenShift with the latest in github, and ActiveMQ crashes with the liquibase scripts:
```
05:39:03,972 [main] INFO BrokerService:870 - Apache ActiveMQ 5.14.0 (kapua, null) is shutdown
ERROR: java.lang.RuntimeException: Failed to execute start task. Reason: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
java.lang.RuntimeException: Failed to execute start task. Reason: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:91)
at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.activemq.console.command.ShellCommand.runTask(ShellCommand.java:154)
at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.activemq.console.command.ShellCommand.main(ShellCommand.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.activemq.console.Main.runTaskClass(Main.java:262)
at org.apache.activemq.console.Main.main(Main.java:115)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:62)
at org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin.installPlugin(KapuaBrokerSecurityPlugin.java:58)
at org.apache.activemq.broker.BrokerService.addInterceptors(BrokerService.java:2445)
at org.apache.activemq.broker.BrokerService.createBroker(BrokerService.java:2306)
at org.apache.activemq.broker.BrokerService.getBroker(BrokerService.java:1017)
at org.apache.activemq.broker.BrokerService.getAdminConnectionContext(BrokerService.java:2576)
at org.apache.activemq.broker.BrokerService.startVirtualConsumerDestinations(BrokerService.java:2717)
at org.apache.activemq.broker.BrokerService.startDestinations(BrokerService.java:2567)
at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:726)
at org.apache.activemq.broker.BrokerService.startBroker(BrokerService.java:720)
at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623)
at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:88)
... 10 more
```


Not sure if this is the same or similar, if I should open a new issue, or if I'm just doing something stupid (totally plausible).  Any thoughts?

**Comment by ccustine** [comment]
@BcGovBrian I just encountered the same issue and created #345. I think they are different issues but I could be wrong.

**Comment by hekonsek** [comment]
OpenShift issues has been resolved and everything is supposed to work as expected in this (OpenShift) environment. If not, please reopen #345.

When it comes to Vagrant and DB schema - broker's Liquibase client relies on `DefaultConfigurableJdbcConnectionUrlResolver` to resolve JDBC URL. Which in turn uses `SystemSettingKey.DB_SCHEMA_ENV / SystemSettingKey.DB_SCHEMA` [1] properties to resolve schema. Have you set those to a proper value in Vagrant then?

[1] https://github.com/eclipse/kapua/blob/7d6ec938886bf63a4a3c64e7ec405ff16f6662c3/commons/src/main/java/org/eclipse/kapua/commons/jpa/DefaultConfigurableJdbcConnectionUrlResolver.java#L50

**Comment by lorthirk** [comment]
As you can see from the logs in [my previous comment](https://github.com/eclipse/kapua/issues/329#issuecomment-283070270) (line 4), the SystemSettingKey.DB_SCHEMA is correctly set in Vagrant, since the `resolveJdbcUrl()` returns  `jdbc:h2:tcp://192.168.33.10:3306/kapuadb;schema=kapuadb`. I also debugged the broker while it boots, and despite the jdbcUrl contains `schema=kapuadb` at the end, it seems that no schema is actually set for the `connection` object:

![schermata 2017-03-03 alle 16 13 04](https://cloud.githubusercontent.com/assets/8140139/23556319/8382545e-002c-11e7-8105-c90d84843248.png)

![schermata 2017-03-03 alle 16 15 13](https://cloud.githubusercontent.com/assets/8140139/23556445/f2802ef8-002c-11e7-86d5-54f34094713f.png)

![schermata 2017-03-03 alle 16 17 15](https://cloud.githubusercontent.com/assets/8140139/23556444/f27e6000-002c-11e7-8f6d-f88e15ce9d88.png)

At this point, the only thing I can think about is a different H2 JDBC driver that ignores the schema attribute of the connection string.

**Comment by hekonsek** [comment]
Hmmm, so it seems to be Liquibase client issue then. I will try to see how can we convince Liquibase client to apply this schema. This is certainly possible, as Maven plugin is able to do it.

As a workaround until I fix this, you can comment out update() invocation from broker code or switch your Vagrant to use public schema.

**Comment by lorthirk** [comment]
@riccardomodanese is suggesting:

`liquibase.getDatabase().setDefaultSchemaName("kapuadb");`

This fixes the issue indeed. The only caveat is that we really should parametrize it, so the constructor signature should be updated to accept the schema name as well.

**Comment by hekonsek** [comment]
Done. See https://github.com/eclipse/kapua/issues/346#issuecomment-284845904 .
