### ISSUE TITLE
Broker not starting in OpenShift

### ISSUE THREAD

**Issue by ccustine** [eclipse/kapua#345]
Related to the move to the embedded Liquibase client I'm certain. Seems like the sql files are not present at all where the service is looking for them.
```
19:58:11,233 [main] INFO  KapuaBrokerSecurityPlugin:53  - >> installPlugin org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin
19:58:11,406 [main] INFO  Reflections:229  - Reflections took 14 ms to scan 6 urls, producing 728 keys and 731 values
19:58:11,413 [main] ERROR BrokerService:626  - Failed to start Apache ActiveMQ ([kapua, null], java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory))
19:58:11,414 [main] INFO  BrokerService:807  - Apache ActiveMQ 5.14.0 (kapua, null) is shutting down
19:58:11,415 [main] INFO  TransportConnector:294  - Connector mqtt stopped
19:58:11,415 [main] INFO  TransportConnector:294  - Connector mqtts stopped
19:58:11,415 [main] INFO  TransportConnector:294  - Connector tcp stopped
19:58:11,415 [main] INFO  TransportConnector:294  - Connector ws stopped
19:58:11,415 [main] INFO  PListStoreImpl:357  - PListStore:[/maven/data/kapua/tmp_storage] stopped
19:58:11,415 [main] INFO  KahaDBStore:261  - Stopping async queue tasks
19:58:11,416 [main] INFO  KahaDBStore:275  - Stopping async topic tasks
19:58:11,416 [main] INFO  KahaDBStore:303  - Stopped KahaDB
19:58:11,462 [main] INFO  BrokerService:868  - Apache ActiveMQ 5.14.0 (kapua, null) uptime 0.399 seconds
19:58:11,463 [main] INFO  BrokerService:870  - Apache ActiveMQ 5.14.0 (kapua, null) is shutdown
ERROR: java.lang.RuntimeException: Failed to execute start task. Reason: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
java.lang.RuntimeException: Failed to execute start task. Reason: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
	at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:91)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.runTask(ShellCommand.java:154)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.main(ShellCommand.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.activemq.console.Main.runTaskClass(Main.java:262)
	at org.apache.activemq.console.Main.main(Main.java:115)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:62)
	at org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin.installPlugin(KapuaBrokerSecurityPlugin.java:58)
	at org.apache.activemq.broker.BrokerService.addInterceptors(BrokerService.java:2445)
	at org.apache.activemq.broker.BrokerService.createBroker(BrokerService.java:2306)
	at org.apache.activemq.broker.BrokerService.getBroker(BrokerService.java:1017)
	at org.apache.activemq.broker.BrokerService.getAdminConnectionContext(BrokerService.java:2576)
	at org.apache.activemq.broker.BrokerService.startVirtualConsumerDestinations(BrokerService.java:2717)
	at org.apache.activemq.broker.BrokerService.startDestinations(BrokerService.java:2567)
	at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:726)
	at org.apache.activemq.broker.BrokerService.startBroker(BrokerService.java:720)
	at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623)
	at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:88)
	... 10 more
Caused by: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:57)
	... 21 more
ERROR: java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
java.lang.RuntimeException: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:62)
	at org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin.installPlugin(KapuaBrokerSecurityPlugin.java:58)
	at org.apache.activemq.broker.BrokerService.addInterceptors(BrokerService.java:2445)
	at org.apache.activemq.broker.BrokerService.createBroker(BrokerService.java:2306)
	at org.apache.activemq.broker.BrokerService.getBroker(BrokerService.java:1017)
	at org.apache.activemq.broker.BrokerService.getAdminConnectionContext(BrokerService.java:2576)
	at org.apache.activemq.broker.BrokerService.startVirtualConsumerDestinations(BrokerService.java:2717)
	at org.apache.activemq.broker.BrokerService.startDestinations(BrokerService.java:2567)
	at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:726)
	at org.apache.activemq.broker.BrokerService.startBroker(BrokerService.java:720)
	at org.apache.activemq.broker.BrokerService.start(BrokerService.java:623)
	at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:88)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.runTask(ShellCommand.java:154)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.main(ShellCommand.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.activemq.console.Main.runTaskClass(Main.java:262)
	at org.apache.activemq.console.Main.main(Main.java:115)
Caused by: java.io.FileNotFoundException: /maven/tmp/kapua-liquibase/athz_domain_actions.sql (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:57)
	... 21 more
```

**Comment by ccustine** [comment]
@hekonsek This issue can be fixed with permissions similar to the other images, ie:
```
<runCmds>
	<run><![CDATA[
	chown -R kapua:kapua /maven && \
	chmod -R a+rw /maven && \
	find /maven -type d -exec chmod a+x {} +
	]]></run>
</runCmds>
```
However, even after that fix, I encounter more issues so it would be nice to get this tested and fixed in OpenShift. After fixing this, it seems like the create for the user table tries to run twice. If this can't be reproduced, I will gladly create a separate issue.

**Comment by ctron** [comment]
+1 for a separate issue

**Comment by ctron** [comment]
Btw .. are you working with PR #288? This code from above looks more like a piece from the PR instead of the main `develop` branch.

**Comment by ctron** [comment]
Applying the change, re-building, re-uploading and re-creating my OpenShift instance seem to work fine.

**Comment by hekonsek** [comment]
Works on my OpenShift instance as well. I'm closing this issue. If somebody still encounter issues in OpenShift, feel free to reopen the issue.

**Comment by ccustine** [comment]
@ctron Yeah, I pulled #288 to my fork. I'm sorry, I should have realized that. Thanks to you and @hekonsek for merging #288 and fixing this issue!
