### ISSUE TITLE
kapua-broker : Unable to locate resource 'kapua-broker-setting.properties'

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [eclipse/kapua#351]
The latest updates have impacted the broker with the following error when clients attempt to publish:

22:18:19,407 [ActiveMQ NIO Worker 9] WARN  AbstractKapuaSetting:59  - Unable to locate resource 'kapua-broker-setting.properties'
22:18:19,408 [ActiveMQ NIO Worker 9] ERROR AbstractKapuaSetting:64  - Error loading PropertiesConfiguration
java.lang.IllegalArgumentException: Unable to locate resource: 'kapua-broker-setting.properties'
	at org.eclipse.kapua.commons.setting.AbstractKapuaSetting.<init>(AbstractKapuaSetting.java:60)
	at org.eclipse.kapua.broker.core.setting.BrokerSetting.<init>(BrokerSetting.java:27)
	at org.eclipse.kapua.broker.core.setting.BrokerSetting.getInstance(BrokerSetting.java:36)
	at org.eclipse.kapua.broker.core.plugin.DefaultConnectorDescriptionProvider.<init>(DefaultConnectorDescriptionProvider.java:68)
	at org.eclipse.kapua.broker.core.plugin.ConnectorDescriptorProviders.locateProvider(ConnectorDescriptorProviders.java:71)

**Comment by BcGovBrian** [comment]
Looks like the file is in `broker-core/src/test/resources`. Is it possible that it just needs to be moved to `broker-core/src/main/resources` ?

Or perhaps it was dropped in the wrong folder? :)

**Comment by ctron** [comment]
Sorry for that hickup. Actually there is no need for a configuration in the broker plugin. But Kapua throws an exception when the file is not present. So I did move the empty file to the `src/main/resources` folder to fix it.

Lazy loading of this class and the fact that it was available for the unit tests made this problem only show up when a gateway connected.
