### ISSUE TITLE
Vagrant images don't work on CentOS/RHEL/Fedora

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#356]
Installing Vagrant and running the setup fails on CentOS/RHEL/Fedora with the following error:

```
[jreimann@dhcp-64-80 vagrant]$ sudo ./start.sh base-box
======> create/update base box
Creating base kapua box named  trusty64/kapua-dev-box-0.1  ...
========================
/home/jreimann/git/kapua/dev-tools/src/main/vagrant/baseBox/kapua-box-tmp
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: [:libvirt]
==> default: translation missing: en.vagrant_libvirt.package_domain
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/package_domain.rb:17:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/package_domain.rb:17:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/machine.rb:225:in `action_raw'
	from /usr/share/vagrant/lib/vagrant/machine.rb:200:in `block in action'
	from /usr/share/vagrant/lib/vagrant/environment.rb:561:in `lock'
	from /usr/share/vagrant/lib/vagrant/machine.rb:186:in `call'
	from /usr/share/vagrant/lib/vagrant/machine.rb:186:in `action'
	from /usr/share/vagrant/plugins/commands/package/command.rb:83:in `package_vm'
	from /usr/share/vagrant/plugins/commands/package/command.rb:72:in `block in package_target'
	from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /usr/share/vagrant/plugins/commands/package/command.rb:70:in `package_target'
	from /usr/share/vagrant/plugins/commands/package/command.rb:44:in `execute'
	from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
	from /usr/share/vagrant/lib/vagrant/environment.rb:302:in `cli'
	from /usr/share/vagrant/bin/vagrant:174:in `<main>'
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'trusty64/kapua-dev-box-0.1' (v0) for provider: 
    box: Downloading: trusty64-kapua-dev-0.1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/jreimann/git/kapua/dev-tools/src/main/vagrant/baseBox/kapua-box-tmp/trusty64-kapua-dev-0.1.box
==> default: Remove stale volume...
==> default: Domain is not created. Please run `vagrant up` first.
... done.
```

**Comment by mcarrer** [comment]
CentOS 7 support was added by PR #706
