### ISSUE TITLE
New data storage causes "Could not initialize class org.elasticsearch.Version"

### ISSUE THREAD

**Issue by ccustine** [eclipse/kapua#364]
Related to #354 , this message occurs on every message sent. They key part seems to be:
"Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.Version"

The stack has messages from ES TransportClient so the jar is obviously in the classpath, but I'm not sure what else could cause this.
```
05:20:01,387 [Camel (camelContext) thread #1 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] WARN  ErrorMessageListener:92  - Exception:
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-kapua-broker-1-v9m18-36852-1489032973960-0-869][JmsMessage[JmsMessageID: ID:kapua-broker-1-v9m18-46134-1489032976487-3:379:-1:1:432]]
	at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1668)
	at org.apache.camel.impl.DefaultExchange.setException(DefaultExchange.java:347)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:254)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:38)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:117)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:689)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:649)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:619)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:307)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:245)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1144)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1136)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1033)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.Version
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:129)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.EsTransportClientProvider.getEsClient(EsTransportClientProvider.java:54)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.EsTransportClientProvider.<init>(EsTransportClientProvider.java:94)
	at sun.reflect.GeneratedConstructorAccessor98.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.ElasticsearchClient.getInstance(ElasticsearchClient.java:51)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.EsSchema.synch(EsSchema.java:350)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.DatastoreMediator.getMetadata(DatastoreMediator.java:133)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreFacade.store(MessageStoreFacade.java:135)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:80)
	at org.eclipse.kapua.broker.core.listener.DataStorageMessageProcessor.processMessage(DataStorageMessageProcessor.java:73)
	at org.eclipse.kapua.broker.core.listener.DataStorageMessageProcessor.processMessage(DataStorageMessageProcessor.java:32)
	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	... 34 more
```

**Comment by riccardomodanese** [comment]
Hi Chris, could you check if you have the elasticsearch jar under the broker lib/extra directory?
Are you using the demo or the develop box?
This pr branch was merged and deleted yesterday. Which branch are you testing now?
Did you create both the vagrant base box and the vagrant develop/demo box?

**Comment by ctron** [comment]
It looks good to me in the docker images.

**Comment by ccustine** [comment]
I built new images tonight from current develop branch and I still have this issue. I verified that I have elasticsearch-2.3.4.jar in lib/extra. I am building and using docker images in Openshift, but I wouldn't think this should be any different from the regular Docker images. Let me know if there is something else I can try to help troubleshoot this.

**Comment by ccustine** [comment]
I have also tested this against plain Docker container and the problem still exists so I am certain this is not Openshift specific. I will try to do some tests against the Vagrant VM later as well.

**Comment by ctron** [comment]
I just reproduced this issue with a fresh `develop` build, running in a simple docker container. With the same (failing) results.

**Comment by ctron** [comment]
My steps to reproduce are:

1) `mvn clean install -Pdev -DsktipTests`
1) `mvn -Pdocker -f assembly`
1) `docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql`
1) `docker run -ti --name kapua-broker --link kapua-sql:db -p 1883:1883 kapua/kapua-broker
`
1) Drop https://dentrassi.de/download/kura/de.dentrassi.kura.addons.example.publisher_0.2.3-SNAPSHOT.dp into a running Kura instance
1) Connect Kura to the broker

**Comment by ctron** [comment]
I have a hunch that this could be cause by "lucene-core" missing in the classpath.

**Comment by ctron** [comment]
Ok .. I am one step closer ... but there is a whole bunch of dependencies missing ...

**Comment by ctron** [comment]
The exceptions regarding missing classes are gone now. So I guess we can close this issue.

Although I still run into issues due due to a missing Elasticsearch instance:
```
12:07:31,875 [Camel (camelContext) thread #5 - JmsConsumer[Consumer.eurotech:mainRoutelisteners:EXACTLY_ONCE.VirtualTopic.%3E]] ERROR DataStorageMessageProcessor:74  - An error occurred while storing message: INTERNAL_ERROR
org.eclipse.kapua.KapuaException: An internal error occurred: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}].
	at org.eclipse.kapua.KapuaException.internalError(KapuaException.java:155)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:83)
	at org.eclipse.kapua.broker.core.listener.DataStorageMessageProcessor.processMessage(DataStorageMessageProcessor.java:69)
	at org.eclipse.kapua.broker.core.listener.DataStorageMessageProcessor.processMessage(DataStorageMessageProcessor.java:1)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:38)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:117)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:689)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:649)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:619)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:307)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:245)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1144)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1136)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1033)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.EsSchema.synch(EsSchema.java:354)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.DatastoreMediator.getMetadata(DatastoreMediator.java:133)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreFacade.store(MessageStoreFacade.java:135)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:80)
	... 42 more

```

But I guess that is a different story.

**Comment by ccustine** [comment]
I have the same results, but we are definitely getting farther so I will close this issue and create a new one.

**Comment by ctron** [comment]
Yes, I have a PR for tomorrow fixing some parts of the ES Transport Provider. But I want to test that a bit more.

**Comment by riccardomodanese** [comment]
Hi @ctron, we are currently working on the datstore transport client to add support also for the rest client, so which changes are you doing?
It should be better if you don't change the code since may conflict with what we are doing now.

**Comment by riccardomodanese** [comment]
I try to explain better what we are currently doing.
Since the Elasticsearch rest client is widely used by the comunity we are introducing the rest client support in the Kapua datastore feature.
Then, we are decoupling the transport layer from the datastore code adding a new module to allow us to use, with the same datastore code, a transport client or a rest client.
In that way is it possible to use the Elasticsearch transport client or the rest client by a configuration parameter.
For this reason the current datstore code is under heavy refactoring.
If there is some dependency issue in the Elasticsearch transport layer the pr shouldn't interfere whith our refactoring, so you can proceed without any problem.
