### ISSUE TITLE
Trouble pushing data to Elasticsearch

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#382]
Hooking up Kura pushing data to Elasticsearch brings up the following exception in Elasticsearch:

```
[2017-03-16 13:21:42,022][DEBUG][action.admin.indices.mapping.put] [Projector] failed to put mappings on indices [[.1]], type [metric]
java.lang.IllegalArgumentException: mapper [metric.value] of different type, current_type [long], merged_type [double]
	at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:378)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.doMerge(NumberFieldMapper.java:301)
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:364)
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:53)
	at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:60)
	at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528)
	at org.elasticsearch.index.mapper.object.RootObjectMapper.doMerge(RootObjectMapper.java:277)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501)
	at org.elasticsearch.index.mapper.object.RootObjectMapper.merge(RootObjectMapper.java:272)
	at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:112)
	at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:376)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:260)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-03-16 13:21:42,026][DEBUG][action.bulk              ] [Projector] [.1][1] failed to execute bulk item (index) index {[.1][metric][ZcoaQ9v9d4xPWTs35MmyJ8RlV8gS0aqJ3rwZ55yZBA8=], source[{"scope_id":"AQ","client_id":"jreimann-puddlejumper","channel":"camel/example","metric":{"name":"doubleValue.dbl","type":"double","value":10.418649552669573,"timestamp":"2017-03-16T13:21:41.806Z","message_id":"4afb52de-14fd-4494-851b-e5520fa24dd4"}}]}
java.lang.IllegalArgumentException: mapper [metric.value] of different type, current_type [long], merged_type [double]
	at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:378)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.doMerge(NumberFieldMapper.java:301)
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:364)
	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:53)
	at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:60)
	at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528)
	at org.elasticsearch.index.mapper.object.RootObjectMapper.doMerge(RootObjectMapper.java:277)
	at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501)
	at org.elasticsearch.index.mapper.object.RootObjectMapper.merge(RootObjectMapper.java:272)
	at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:112)
	at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:376)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:260)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcarrer** [comment]
ES Data Store is currently passing unit tests.
Closing the issue.
