### ISSUE TITLE
Failing datastore tests

### ISSUE THREAD

**Issue by muros-ct** [eclipse/kapua#482]
While checking log of datastore-internal tests that are failing on Hudson, and as I know only on Hudson (https://ci.eclipse.org/kapua), I found one interesting Exception (see below).
I thought that tests are failing because insert and query were too close and timeout between those would help. But it seams that the problem lies in store method, which fails. 

The interesting part is `Caused by: ElasticsearchTimeoutException[Timeout waiting for task.]`

@riccardomodanese can you take a look?

I will try to reproduce it on local environment. It is namely hard to address the issue if you can't reproduce it on local box.

Original exception form Hudson output:

`
10:18:54,469 [main] ERROR MessageStoreServiceTest:1039  - Message insert exception!
org.eclipse.kapua.KapuaException: An internal error occurred: Timeout waiting for task..
	at org.eclipse.kapua.KapuaException.internalError(KapuaException.java:152)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:83)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceTest.insertMessages(MessageStoreServiceTest.java:1037)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceTest.testMessageStore(MessageStoreServiceTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: ElasticsearchTimeoutException[Timeout waiting for task.]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:70)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:62)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.dao.EsTypeDAO.upsert(EsTypeDAO.java:176)
	at org.eclipse.kapua.service.datastore.internal.elasticsearch.dao.EsMessageDAO.upsert(EsMessageDAO.java:132)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreFacade.store(MessageStoreFacade.java:154)
	at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:81)
	... 34 more
`

**Comment by riccardomodanese** [comment]
Hi Uros,

yes, from the stacktrace it seems that the timeout is occurring during the message insert step.
I suggest to try with an higher query timeout value
    https://github.com/eclipse/kapua/blob/develop/service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/elasticsearch/EsUtils.java#L548
since it’s used also for upstore operation.




Il giorno 19 apr 2017, alle ore 09:35, Uroš Mesarič Kunst <notifications@github.com<mailto:notifications@github.com>> ha scritto:


While checking log of datastore-internal tests that are failing on Hudson, and as I know only on Hudson (https://ci.eclipse.org/kapua), I found one interesting Exception (see below).
I thought that tests are failing because insert and query were too close and timeout between those would help. But it seams that the problem lies in store method, which fails.

The interesting part is Caused by: ElasticsearchTimeoutException[Timeout waiting for task.]

@riccardomodanese<https://github.com/riccardomodanese> can you take a look?

I will try to reproduce it on local environment. It is namely hard to address the issue if you can't reproduce it on local box.

Original exception form Hudson output:

10:18:54,469 [main] ERROR MessageStoreServiceTest:1039 - Message insert exception! org.eclipse.kapua.KapuaException: An internal error occurred: Timeout waiting for task.. at org.eclipse.kapua.KapuaException.internalError(KapuaException.java:152) at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:83) at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceTest.insertMessages(MessageStoreServiceTest.java:1037) at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceTest.testMessageStore(MessageStoreServiceTest.java:174) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.runners.ParentRunner.run(ParentRunner.java:309) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: ElasticsearchTimeoutException[Timeout waiting for task.] at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:70) at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:62) at org.eclipse.kapua.service.datastore.internal.elasticsearch.dao.EsTypeDAO.upsert(EsTypeDAO.java:176) at org.eclipse.kapua.service.datastore.internal.elasticsearch.dao.EsMessageDAO.upsert(EsMessageDAO.java:132) at org.eclipse.kapua.service.datastore.internal.MessageStoreFacade.store(MessageStoreFacade.java:154) at org.eclipse.kapua.service.datastore.internal.MessageStoreServiceImpl.store(MessageStoreServiceImpl.java:81) ... 34 more

**Comment by Coduz** [comment]
Hi @muros-ct  and @riccardomodanese 

Has this been fixed? 

Regards, 

_Alberto_

**Comment by muros-ct** [comment]
A lot of refactoring has been done on datastore as well as tests. Issue was resolved.
This issue as such can be closed.

**Comment by Coduz** [comment]
Thanks :)
