### ISSUE TITLE
Travis builds failing with "killed"

### ISSUE THREAD

**Issue by ctron** [eclipse/kapua#696]
Most recent Travis CI builds fail with a simple "killed" message:

For example see: https://travis-ci.org/eclipse/kapua/builds/246999354#L1375
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:22 min
[INFO] Finished at: 2017-06-26T08:23:22+00:00
[INFO] Final Memory: 84M/431M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project kapua-qa: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kapua-qa
```

**Comment by ctron** [comment]
After upgrading to surefire 2.20 the error message contains more detail:

https://travis-ci.org/ctron/kapua/builds/247040250#L1298
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:28 min
[INFO] Finished at: 2017-06-26T10:17:49+00:00
[INFO] Final Memory: 83M/426M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project kapua-security-shiro: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/ctron/kapua/service/security/shiro/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/ctron/kapua/service/security/shiro && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/travis/build/ctron/kapua/service/security/shiro/target/jacoco.exec -jar /home/travis/build/ctron/kapua/service/security/shiro/target/surefire/surefirebooter3950181182677956264.jar /home/travis/build/ctron/kapua/service/security/shiro/target/surefire 2017-06-26T10-10-05_549-jvmRun1 surefire1409767628649669834tmp surefire_64908554155996654704tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] Scenario: Delete nonexisting role permission
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/ctron/kapua/service/security/shiro && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/travis/build/ctron/kapua/service/security/shiro/target/jacoco.exec -jar /home/travis/build/ctron/kapua/service/security/shiro/target/surefire/surefirebooter3950181182677956264.jar /home/travis/build/ctron/kapua/service/security/shiro/target/surefire 2017-06-26T10-10-05_549-jvmRun1 surefire1409767628649669834tmp surefire_64908554155996654704tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] Scenario: Delete nonexisting role permission
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
```

Googling for that exit code comes up with "SIGKILL" being the reason, which is most likely the OOM killer, which would be Travis in our case. So the assumption that we are hitting Travis' 3GB limit may be correct.

**Comment by ctron** [comment]
Fixing the memory limit in the build seemed to work some time ago.
