### ISSUE TITLE
java.lang.NoSuchMethodError: No static method join

### ISSUE THREAD

**Issue by amitghodke90** [eclipse/kapua#732]
@Coduz 
[new issue.txt](https://github.com/eclipse/kapua/files/1130705/new.issue.txt)

**Comment by ctron** [comment]
Content from the file link:

```
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)
Ljava/lang/String; in class Ljava/lang/String;
 or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)

07-07 15:52:12.955 18693-18693/? W/System.err: java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.sendBirthCertificate(KuraBirthCertificateModule.java:160)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.applicationAdded(KuraBirthCertificateModule.java:125)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.org_eclipse_kapua_gateway_client_spi_AbstractClient_lambda$notifyAddApplication$1(AbstractClient.java:93)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.-$Lambda$KStGMhXnF-IIdxWAA04teiOckp0$5.$m$0(Unknown Source)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.-$Lambda$KStGMhXnF-IIdxWAA04teiOckp0$5.accept(Unknown Source)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.fireModuleEvent(AbstractClient.java:85)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.notifyAddApplication(AbstractClient.java:93)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient.internalBuildApplication(AbstractClient.java:148)
07-07 15:52:12.955 18693-18693/? W/System.err:     at org.eclipse.kapua.gateway.client.spi.AbstractClient$2.build(AbstractClient.java:134)
07-07 15:52:12.955 18693-18693/? W/System.err:     at amittestapp.admin.example.com.tcpconnectdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:58)
07-07 15:52:12.955 18693-18693/? W/System.err:     at amittestapp.admin.example.com.tcpconnectdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:39)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6679)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-07 15:52:12.955 18693-18693/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
07-07 15:52:12.955 18693-18693/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-07 15:52:12.955 18693-18693/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-07 15:52:12.955 18693-18693/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ctron** [comment]
Kapua does require Java 8. So when you are targeting Android, you will need to make sure that you are using Java 8 compatibility. Also see: https://developer.android.com/studio/write/java8-support.html#supported_features

However, as Android might only provide a sub-set of Java 8, I am not sure that Android is fully supported by the SDK. However if you feel the need for modifications, I would be helpful if you could provide some input or offer changes (pull requests, contributions) by yourself.

In order to understand your exact issue it would also be helpful to know your android target environment.

**Comment by amitghodke90** [comment]
@ctron 

I have change target version of java to java 8 for my android project and already made it  jack enable as described in  https://developer.android.com/studio/write/java8-support.html#supported_features

the issue is String.join method is not supported because String.join was added in Java 8, which is why you can't use it in Android.(source -https://stackoverflow.com/questions/33802971/alternative-for-string-join-in-android ).
I my android minimum sdk version is api 19 and will be targeting to  api 21 .

**Comment by amitghodke90** [comment]
@ctron ??

**Comment by amitghodke90** [comment]
hello @ctron  
i have installed latest android studio 3.0 and run this app still getting same error sending you screen shot
![screenshot from 2017-07-10 12-33-28](https://user-images.githubusercontent.com/25997114/28006289-4cb37390-656c-11e7-9523-6e819334fbd9.png)

**Comment by ctron** [comment]
As "jack" is deprecated I suggest you follow the advice from Android Studio and remove it, maybe that solves the issue. Did you also upgrade the Gradle build plugin to some 3.0 version?

**Comment by amitghodke90** [comment]
@ctron 
yes i changed the gradle plugin version to 4.1 and removed the jack option from app.gradle file and enables java8 options by  android.enableDesugar=true in gradle.properties but the same result no such method error.

**Comment by amitghodke90** [comment]
?

**Comment by ctron** [comment]
I think you are talking about something different. From what I know there is only a 3.0 version of the android gradle plugin.

**Comment by amitghodke90** [comment]
yeah..its gradle version i talked about its 4.1 and android gradle plugin version is 3.0.0-alpha5 which is latest ' classpath 'com.android.tools.build:gradle:3.0.0-alpha5'

**Comment by amitghodke90** [comment]
@ctron 
i am still facing same issue String.join method is not supported in android with java 8 .can we replace that method with another.?

**Comment by ctron** [comment]
I just validated the setup. Using Android Studio 3.0 Canary 5, disabling the Jack toolchain, using Android target SDK 24, running on Android O, using the Android Gradle Plugin 3.0-alpha5 **does** work!

I suggest to replicate this and then start modifying your environment towards your target settings.

**Comment by ctron** [comment]
In any case you can make a fork of the project and patch it in a way which helps you to work around this.

**Comment by amitghodke90** [comment]
@ctron one more error due to java 8 

07-11 14:52:08.706 19575-19575/com.example.amit.mqttdemo W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

**Comment by amitghodke90** [comment]
@Coduz @lorthirk 
 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                                                                               at org.eclipse.kapua.gateway.client.Payload$Builder.<init>(Payload.java:34)
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:77)
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:39)
                                                                               at android.app.Activity.performCreate(Activity.java:6679)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.example.amit.mqttdemo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.amit.mqttdemo-2/lib/x86, /system/lib, /vendor/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                               at org.eclipse.kapua.gateway.client.Payload$Builder.<init>(Payload.java:34) 
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:77) 
                                                                               at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:39) 
                                                                               at android.app.Activity.performCreate(Activity.java:6679) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by amitghodke90** [comment]
@ctron  i got expected output and able to send telemetry data to kapua i fix the bug.

**Comment by noumanpowersoft19** [comment]
@ctron  @amitghodke90 i am not able to connect to kapua from android device using same code. any help will be appreciable . i'll be thankful to both of you. i am tried it from weeks but could'nt get much success
