### ISSUE TITLE
HTTP 500 Internal Server Error :Error while calling configuration api.  http://localhost:8081/doc/#!/Devices/get_0_1_2

### ISSUE THREAD

**Issue by amitghodke90** [eclipse/kapua#767]
```
356397 [qtp1945604815-13] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US 
356399 [qtp1945604815-13] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US 
356400 [qtp1945604815-13] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US 
356401 [qtp1945604815-13] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US 
356401 [qtp1945604815-13] WARN  org.eclipse.kapua.KapuaException - Could not load Exception Messages Bundle for Locale en_US 
356402 [qtp1945604815-13] ERROR o.e.k.a.a.v.r.AbstractKapuaResource - Internal Error 
org.eclipse.kapua.service.device.call.kura.exception.KuraMqttDeviceCallException: Error: 
	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.send(KuraDeviceCallImpl.java:127)
	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.read(KuraDeviceCallImpl.java:50)
	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.read(KuraDeviceCallImpl.java:38)
	at org.eclipse.kapua.service.device.management.commons.call.DeviceCallExecutor.send(DeviceCallExecutor.java:99)
	at org.eclipse.kapua.service.device.management.configuration.internal.DeviceConfigurationManagementServiceImpl.get(DeviceConfigurationManagementServiceImpl.java:100)
	at org.eclipse.kapua.app.api.v1.resources.DeviceManagementConfigurations.getComponent(DeviceManagementConfigurations.java:124)
	at org.eclipse.kapua.app.api.v1.resources.DeviceManagementConfigurations.get(DeviceManagementConfigurations.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
```

**Comment by lorthirk** [comment]
Can you provide the input parameters you're using?

**Comment by amitghodke90** [comment]
hi @lorthirk  ,
this is my

server url :-http://localhost:8081/v1/AQ/devices/Z9UXf0nTht4/configurations
authorization: <access_token>

Getting response as follows 
{
    "code": 500,
    "reason": "Internal Server Error",
    "message": "HTTP 500 Internal Server Error"
}

as log is as above.

**Comment by ctron** [comment]
@amitghodke90 I guess there is a "cause" section on the stack trace, could you provide that as well?

**Comment by amitghodke90** [comment]
[cause.txt](https://github.com/eclipse/kapua/files/1196523/cause.txt)

**Comment by lorthirk** [comment]
In the log file you attached I read:

`Caused by: org.eclipse.paho.client.mqttv3.MqttSecurityException: Bad user name or password`

What credentials are you using for the device?

**Comment by amitghodke90** [comment]
@lorthirk 
i have created simulators. 

by the command  java -jar target/kapua-simulator-kura-*-app.jar -c  "5"  and not asking me any credentials.
i guess it gets default credentials i.e.
Username: kapua-broker
Password: kapua-password

**Comment by amitghodke90** [comment]
105902 [qtp1945604815-16] ERROR o.e.k.s.a.s.r.AccessTokenCredentialsMatcher - Error while validating JWT access token 
org.jose4j.jwt.consumer.InvalidJwtSignatureException: JWS signature is invalid: JsonWebSignature{"alg":"RS256"}->eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5lY2xpcHNlLm9yZy9rYXB1YSIsImlhdCI6MTUwMTc1Nzk5NCwiZXhwIjoxNTAxNzU5Nzk0LCJzdWIiOiJaRWctQjhIZlpkVSIsInNJZCI6IkFRIn0.I5PZSW06WPoComkhydTiWSaRRqfcfjK_OmhdOGz-ThwQGCsKdQzObEEgDVWKQtXmGj7QZfqJsVpApQEHbpFe8UjIaFpwrjZe99tA906VfK1qiXrGdOszZlvGuDWumyR5-LTDoiwYIqmv9imqqZXqOj87LM-fMpWsefbIH1qn5k2PzYHyO-BMcxV1QSY3-F6IDvY2brX2HoJMNqShLDHlpNQE8EmNgaeV38sk15wtgSi7jHvPW54CSZKhOi8FxJjRzu5zlnjVUec9FpBd6q2J5-mNXk1WO0rIp03peYsAS6PI2GxH9YH56r7sk73K3y3fGUo6TNazMx77cFp9WjUVzQ
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:204)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:395)
	at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:155)
	at org.eclipse.kapua.service.authentication.shiro.realm.AccessTokenCredentialsMatcher.doCredentialsMatch(AccessTokenCredentialsMatcher.java:75)
	at org.apache.shiro.realm.AuthenticatingRealm.assertCredentialsMatch(AuthenticatingRealm.java:597)
	at org.eclipse.kapua.service.authentication.shiro.realm.AccessTokenAuthenticatingRealm.assertCredentialsMatch(AccessTokenAuthenticatingRealm.java:180)
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:578)
	at org.eclipse.kapua.service.authentication.shiro.KapuaAuthenticator.doMultiRealmAuthentication(KapuaAuthenticator.java:58)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at org.apache.shiro.web.filter.authc.AuthenticatingFilter.executeLogin(AuthenticatingFilter.java:53)
	at org.eclipse.kapua.app.api.auth.KapuaTokenAuthenticationFilter.isAccessAllowed(KapuaTokenAuthenticationFilter.java:41)
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:203)
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:178)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
161062 [qtp1945604815-18] ERROR o.e.k.s.a.s.r.AccessTokenCredentialsMatcher - Error while validating JWT access token 
org.jose4j.jwt.consumer.InvalidJwtSignatureException: JWS signature is invalid: JsonWebSignature{"alg":"RS256"}->eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5lY2xpcHNlLm9yZy9rYXB1YSIsImlhdCI6MTUwMTc1Nzk1NCwiZXhwIjoxNTAxNzU5NzU0LCJzdWIiOiJBZyIsInNJZCI6IkFRIn0.VnZIzOppruqe6McnXpCaxhu-heBZXddue8wZ-d6LHj_qu-g-tiUvqNh0iEFr3pdJA0phhAO0_e5J135-4ExeqKPSEarTlro_9gALTM8B1pBzQro7egLFzL-HMh7O9hvdZRNBkZcz1OCYKkS6jdVwTmoGl4D-0caHaxBF0FtZUi685AFTLaotQn1vFV5KQp-y2EGLQJFeIyKlx0RzKNdNSELKATq4Z6rdzrv8LW2IdH_y3LcvaFN1PKmkjMH-gKX2gUaWDNNgEIaZFq_wNBkW2oDJUiKI5Iayly7en1ptYB1FsyhvNRBbOZprSgrSfj9CrJpShq4GbVQpKV6JtAu5OQ
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:204)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:395)
	at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:155)
	at org.eclipse.kapua.service.authentication.shiro.realm.AccessTokenCredentialsMatcher.doCredentialsMatch(AccessTokenCredentialsMatcher.java:75)
	at org.apache.shiro.realm.AuthenticatingRealm.assertCredentialsMatch(AuthenticatingRealm.java:597)
	at org.eclipse.kapua.service.authentication.shiro.realm.AccessTokenAuthenticatingRealm.assertCredentialsMatch(AccessTokenAuthenticatingRealm.java:180)
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:578)
	at org.eclipse.kapua.service.authentication.shiro.KapuaAuthenticator.doMultiRealmAuthentication(KapuaAuthenticator.java:58)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at org.apache.shiro.web.filter.authc.AuthenticatingFilter.executeLogin(AuthenticatingFilter.java:53)
	at org.eclipse.kapua.app.api.auth.KapuaTokenAuthenticationFilter.isAccessAllowed(KapuaTokenAuthenticationFilter.java:41)
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:203)
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:178)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lorthirk** [comment]
Please use [Github Markdown](https://guides.github.com/features/mastering-markdown/) to post such messages, or attach them as files. If you post them as raw text they are almost undreadable.

Anyway, the error message is pretty clear: the JWS (JsonWebSignature) is invalid. Are you using an AccessToken generated by the same AuthorizationService instance that also has to verify it? Has the service been restarted between the generation of the AccessToken and its verification during the REST API call?

**Comment by ctron** [comment]
I updated the comment.

**Comment by amitghodke90** [comment]
@lorthirk  
i dont have any idea whether Has the service been restarted between the generation of the AccessToken and its verification during the REST API call?how can i determine ?
but what is the cause of first issue i posted ? can you help me in that?.

**Comment by lorthirk** [comment]
The main cause is that the AccessToken (that is a JWT) signature can't be verified. It could be because the public and private keys changed between the generation of the AccessToken and its verification, and IIRC this only happens if AuthenticationServer is restarted; other causes may involve incorrectly forged AccessTokens.

**Comment by amitghodke90** [comment]
then what should i do ?is there any solution?

**Comment by Coduz** [comment]
You have to refresh the token by doing another login or provide the same public/private keys between restarts. In the second solution by the way the token will expire after a while, so i'll need to refresh it anyway.

** Note: I think that we can see the issue/new messages even without direct tagging, thanks.**

**Comment by amitghodke90** [comment]
Thanks ,
from your solutions i understand that the token is getting expired ,but same token is working for another apis then how its possible. if its expired then other apis are giving the results.
What are the public and private keys where we are going to specify it. and how we come to know when service restarts .

**Comment by Coduz** [comment]
Service restarts when you restart it.
By what you are saying I suppose that you have multiple instances of REST api, right?
For public/private keys and JWT signature please refer to [JWT Documentation](https://jwt.io/)

**Comment by amitghodke90** [comment]
I am testing the apis using Postman rest client 
i am login in by  calling  login api (http://loclahost:8081/v1/authentication/user) it gives me 
access token . same token  i am using to call http://localhost:8081/v1/AQ/devices?offset=0&limit=50 this api given swagger ui and its giving me list of connected devices.
again using same access token to call http://loclahost:8081/v1/AQ/devices/AMxkFU4gIiUM/configurations and getting error as posted

**Comment by amitghodke90** [comment]
I am calling the apis specified in swagger ui using Postman rest client
i am logged in by calling login api (http://localhost:8081/v1/authentication/user) it gives me
access token . same token i am using to call http://localhost:8081/v1/AQ/devices?offset=0&limit=50 this api and its giving me list of connected devices.
again using same access token to call http://localhost:8081/v1/AQ/devices/AMxkFU4gIiUM/configurations and getting error as posted .
in that case when service is restarting

**Comment by lorthirk** [comment]
@amitghodke90 Why did you post again the same content? Did you update something I am missing perhaps?

**Comment by amitghodke90** [comment]
i am awaiting for reply.

**Comment by lorthirk** [comment]
Posting the same content twice does not help.

**Comment by amitghodke90** [comment]
ok.

**Comment by lorthirk** [comment]
I tested the methods and I can successfully get the configurations for the device I have attached. 

Now that I see the URLs you are using, what username and password are you using to generate the AccessToken?

**Comment by amitghodke90** [comment]
I have created new user with my name : amit pass:- Amit@ghodke90
and assigned the admin role to it .then i am using these credentials 
username : amit
pass:- Amit@ghodke90

**Comment by lorthirk** [comment]
Have you already tried to pull the latest changes from `develop` and test against those sources?

**Comment by amitghodke90** [comment]
no!.
which branch in which branch the changes are made.

**Comment by lorthirk** [comment]
What changes, sorry?

You should always follow the `develop` branch.

**Comment by amitghodke90** [comment]
i again cloned the main kapua repository and after running login api its giving error
not able to login then how can i test further apis.

![selection_004](https://user-images.githubusercontent.com/25997114/29121610-e2d1f676-7d2c-11e7-9a9c-beb3b1259a61.png)

**Comment by amitghodke90** [comment]
i have again cloned kapua repository to separate location then  after running same issue occurred.
![selection_006](https://user-images.githubusercontent.com/25997114/29123985-2212652a-7d35-11e7-8c80-f35867c71ed4.png)

**Comment by Coduz** [comment]
The stacktrace is partial, but from what I can see there is no problem with the token. 
There is some error on the device interaction.

**Comment by lorthirk** [comment]
Also, I see you're using Docker as a container for the Kapua components. Can you confirm you correctly rebuild the Docker images after building Kapua, as per [README.md](https://github.com/eclipse/kapua/blob/develop/assembly/README.md)?

**Comment by amitghodke90** [comment]
yes rebuilt because there in first build i was Getting response as follows
{
"code": 500,
"reason": "Internal Server Error",
"message": "HTTP 500 Internal Server Error"
}
and after new rebuilt getting as shown in screenshot

**Comment by lorthirk** [comment]
Is the device (a simulator, right?) actually connected to the broker?

**Comment by amitghodke90** [comment]
yes devices are  connected to broker one is simulator another is android  device.

**Comment by lorthirk** [comment]
Can you inspect the `kapua-api` container log with `docker logs -f kapua-api` and post the full stack trace?

**Comment by amitghodke90** [comment]
after inspecting as you suggested.
[error.txt](https://github.com/eclipse/kapua/files/1231143/error.txt)

**Comment by lorthirk** [comment]
Now the errors are completely different. You have various occurrences of 
```
Caused by: org.eclipse.kapua.transport.mqtt.MqttClientException: Error: org.eclipse.kapua.transport.message.mqtt.MqttTopic@33a6abff
	at org.eclipse.kapua.transport.mqtt.MqttFacade.sendSync(MqttFacade.java:89)
	at org.eclipse.kapua.transport.mqtt.MqttFacade.sendSync(MqttFacade.java:32)
	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.send(KuraDeviceCallImpl.java:115)
	... 84 common frames omitted
```
So clearly the scenario is different from the previous ones.

Also, from it seems that the file you uploaded contains logs from different sources, not stating clearly what such outputs refers to. It looks like it contains a mixture of Docker containers, not indicating which containers are running and how you run them. Moreover your log contains `KapuaLocator` bindings starting at line 417 after some of the errors already occurred, and it sounds suspicious to me: the locator should bind classes as soon as its container starts, but again, without even the slightest glimpse of context I'm not able to understand what's happening.

This is the 34th comment in this issue, and we still have no clue about the context in which you're having such difficulties. I tried to reproduce the issue you initially described and I had no problems doing that, so it must be something on your side. Please, if the context of your questions shifted from the original question, open a new issue; otherwise, provide actual, contextualized reports of what you're doing and what happens when you do that. Otherwise we'll never be able to actually help you and anyone else should occur in your issues.

**Comment by lorthirk** [comment]
Since 20 days have passed from the last reply I'm assuming this can be closed. Please feel free to open new issues if you need it.
