### ISSUE TITLE
liquibase--chagelog script excute error for mysql

### ISSUE THREAD

**Issue by miricy** [eclipse/kapua#821]
**When i update mysql database, there is a error like below:**
 ##
14:54:06.136 [main] INFO  o.e.k.s.l.KapuaLiquibaseClient - 	Master Liquibase files found: 1
14:54:06.136 [main] INFO  o.e.k.s.l.KapuaLiquibaseClient - 		Excuting liquibase script: /work/tmp/kapua-broker-0.3.0-SNAPSHOT/tmp/kapua-liquibase/changelog-system-configurations-master.pre.xml
14:54:19.322 [main] ERROR liquibase - Change Set KapuaDB/changelog-system-configuration-0.2.0.xml::changelog-system-configuration-0.2.0::eurotech failed.  Error: Error executing SQL CREATE TABLE kapuadb1.sys_configuration (scope_id BIGINT(21) unsigned NOT NULL, id BIGINT(21) unsigned AUTO_INCREMENT NOT NULL, pid VARCHAR(255) NOT NULL, configurations LONGTEXT NULL, created_on TIMESTAMP DEFAULT NOW() NULL, created_by BIGINT(21) unsigned NOT NULL, modified_on TIMESTAMP DEFAULT NOW() NOT NULL, modified_by BIGINT(21) unsigned NOT NULL, optlock INT unsigned NULL, attributes LONGTEXT NULL, properties LONGTEXT NULL, CONSTRAINT PK_SYS_CONFIGURATION PRIMARY KEY (scope_id, id)): Incorrect table definition; there can be only one auto column and it must be defined as a key
liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE kapuadb1.sys_configuration (scope_id BIGINT(21) unsigned NOT NULL, id BIGINT(21) unsigned AUTO_INCREMENT NOT NULL, pid VARCHAR(255) NOT NULL, configurations LONGTEXT NULL, created_on TIMESTAMP DEFAULT NOW() NULL, created_by BIGINT(21) unsigned NOT NULL, modified_on TIMESTAMP DEFAULT NOW() NOT NULL, modified_by BIGINT(21) unsigned NOT NULL, optlock INT unsigned NULL, attributes LONGTEXT NULL, properties LONGTEXT NULL, CONSTRAINT PK_SYS_CONFIGURATION PRIMARY KEY (scope_id, id)): Incorrect table definition; there can be only one auto column and it must be defined as a key
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:56)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:98)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1491)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1474)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:343)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:63)
	at liquibase.Liquibase.update(Liquibase.java:136)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.executeMasters(KapuaLiquibaseClient.java:140)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.loadResourcesStatic(KapuaLiquibaseClient.java:112)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:71)
	at org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin.installPlugin(KapuaBrokerSecurityPlugin.java:68)
	at org.apache.activemq.broker.BrokerService.addInterceptors(BrokerService.java:2446)
	at org.apache.activemq.broker.BrokerService.createBroker(BrokerService.java:2307)
	at org.apache.activemq.broker.BrokerService.getBroker(BrokerService.java:1018)
	at org.apache.activemq.broker.BrokerService.getAdminConnectionContext(BrokerService.java:2577)
	at org.apache.activemq.broker.BrokerService.startVirtualConsumerDestinations(BrokerService.java:2744)
	at org.apache.activemq.broker.BrokerService.startDestinations(BrokerService.java:2568)
	at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:727)
	at org.apache.activemq.broker.BrokerService.startBroker(BrokerService.java:721)
	at org.apache.activemq.broker.BrokerService.start(BrokerService.java:624)
	at org.apache.activemq.xbean.XBeanBrokerService.afterPropertiesSet(XBeanBrokerService.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1700)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1639)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.apache.xbean.spring.context.ResourceXmlApplicationContext.<init>(ResourceXmlApplicationContext.java:64)
	at org.apache.xbean.spring.context.ResourceXmlApplicationContext.<init>(ResourceXmlApplicationContext.java:52)
	at org.apache.activemq.xbean.XBeanBrokerFactory$1.<init>(XBeanBrokerFactory.java:104)
	at org.apache.activemq.xbean.XBeanBrokerFactory.createApplicationContext(XBeanBrokerFactory.java:104)
	at org.apache.activemq.xbean.XBeanBrokerFactory.createBroker(XBeanBrokerFactory.java:67)
	at org.apache.activemq.broker.BrokerFactory.createBroker(BrokerFactory.java:71)
	at org.apache.activemq.broker.BrokerFactory.createBroker(BrokerFactory.java:54)
	at org.apache.activemq.console.command.StartCommand.runTask(StartCommand.java:87)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.runTask(ShellCommand.java:154)
	at org.apache.activemq.console.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.activemq.console.command.ShellCommand.main(ShellCommand.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.activemq.console.Main.runTaskClass(Main.java:262)
	at org.apache.activemq.console.Main.main(Main.java:115)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Incorrect table definition; there can be only one auto column and it must be defined as a key
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2448)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:86)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:49)
	... 55 common frames omitted
14:54:19.494 [main] ERROR o.e.k.s.l.KapuaLiquibaseClient - Error while running Liquibase scripts!
liquibase.exception.MigrationFailedException: Migration failed for change set KapuaDB/changelog-system-configuration-0.2.0.xml::changelog-system-configuration-0.2.0::eurotech:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE kapuadb1.sys_configuration (scope_id BIGINT(21) unsigned NOT NULL, id BIGINT(21) unsigned AUTO_INCREMENT NOT NULL, pid VARCHAR(255) NOT NULL, configurations LONGTEXT NULL, created_on TIMESTAMP DEFAULT NOW() NULL, created_by BIGINT(21) unsigned NOT NULL, modified_on TIMESTAMP DEFAULT NOW() NOT NULL, modified_by BIGINT(21) unsigned NOT NULL, optlock INT unsigned NULL, attributes LONGTEXT NULL, properties LONGTEXT NULL, CONSTRAINT PK_SYS_CONFIGURATION PRIMARY KEY (scope_id, id)): Incorrect table definition; there can be only one auto column and it must be defined as a key
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:376)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:63)
	at liquibase.Liquibase.update(Liquibase.java:136)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.executeMasters(KapuaLiquibaseClient.java:140)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.loadResourcesStatic(KapuaLiquibaseClient.java:112)
	at org.eclipse.kapua.service.liquibase.KapuaLiquibaseClient.update(KapuaLiquibaseClient.java:71)
	at org.eclipse.kapua.broker.core.KapuaBrokerSecurityPlugin.installPlugin(KapuaBrokerSecurityPlugin.java:68)
	at org.apache.activemq.broker.BrokerService.addInterceptors(BrokerService.java:2446)
	at org.apache.activemq.broker.BrokerService.createBroker(BrokerService.java:2307)
	at org.apache.activemq.broker.BrokerService.getBroker(BrokerService.java:1018)
	at org.apache.activemq.broker.BrokerService.getAdminConnectionContext(BrokerService.java:2577)
	at org.apache.activemq.broker.BrokerService.startVirtualConsumerDestinations(BrokerService.java:2744)
	at org.apache.activemq.broker.BrokerService.startDestinations(BrokerService.java:2568)
	at org.apache.activemq.broker.BrokerService.doStartBroker(BrokerService.java:727)

**Comment by Coduz** [comment]
This is probably due to the new definition of `sys_configuration` table which now defines the `id` field as `auto_increment`. 
The new definition seems compatible with H2 db but not with MySQL/MariaDB

**Comment by lorthirk** [comment]
Hi @miricy,

Could you please try PR #827 and see if you have any error?

**Comment by Coduz** [comment]
Sorry I've merged the PR already 😅  

@miricy You should try this on `develop` branch.

**Comment by miricy** [comment]
Thanks, It's ok on develop branch.
